-- =============================================================================
-- Seed ModuleInfoItem : import des fiches FAQ patient (chantier 2026-08-06)
-- =============================================================================
--
-- Import initial des Q/R FAQ patient pour 3 centres :
--   - userProductId=2  -> Radiologie Muzillac (MZC.json)
--   - userProductId=12 -> Cognac / SELAS TESLA (A04.json)
--   - userProductId=15 -> CH Menton La Palmosa (MEN.json)
--
-- Idempotent : chaque INSERT est protege par ON CONFLICT (id) DO NOTHING.
-- Rejouer le script ne cree pas de doublons. En revanche, il ne MET PAS A JOUR
-- les items existants -- pour ecraser un item, DELETE + rerun.
--
-- Bump 'moduleInfoVersion' en fin de script pour declencher le refresh Azure
-- au prochain poll (webhook non declenche depuis SQL, mais Azure re-fetchera).
-- =============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- Centre userProductId=2 (MZC.json)
-- ---------------------------------------------------------------------------
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quel-est-le-nom-complet-de-votre-centre', 2, 'Quel est le nom complet de votre centre ?', 'Radiologie Muzillac', NULL, true, 0, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-complete-de-votre-centre', 2, 'Quelle est l''adresse complète de votre centre ?', '23 bis rue du Général de Gaulle, 56190 Muzillac', NULL, true, 1, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('votre-centre-possede-t-il-un-site-web-et-si-oui-quel-est-son', 2, 'Votre centre possède-t-il un site web et, si oui, quel est son lien ?', 'Oui, www.radiologiemuzillac.com', NULL, true, 2, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelles-sont-les-modalites-d-acces-a-votre-centre-entree-pri', 2, 'Quelles sont les modalités d''accès à votre centre (entrée principale, étage, interphone…) ?', 'Accès direct depuis la rue au 23 bis rue du Général de Gaulle.', NULL, true, 3, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-entree-recommandez-vous-aux-personnes-a-mobilite-redu', 2, 'Quelle entrée recommandez-vous aux personnes à mobilité réduite ?', 'L''entrée principale est accessible aux personnes à mobilité réduite et aux brancards.', NULL, true, 4, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-phrase-dites-vous-au-telephone-au-patient-pour-lui-ex', 2, 'Quelle phrase dites-vous au téléphone au patient pour lui expliquer comment se rendre à votre centre ?', 'Le cabinet de radiologie est situé au 23 bis rue du Général de Gaulle à Muzillac. Un parking est disponible à proximité.', NULL, true, 5, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-phrase-dites-vous-au-telephone-au-patient-pour-lui-2', 2, 'Quelle phrase dites-vous au téléphone au patient pour lui expliquer comment trouver l''entrée de votre centre ?', 'Le cabinet peut être partiellement caché par un immeuble récent, l''entrée se fait directement depuis la rue.', NULL, true, 6, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('existe-t-il-des-difficultes-particulieres-pour-acceder-a-vot', 2, 'Existe-t-il des difficultés particulières pour accéder à votre centre ?', 'Le cabinet peut être partiellement masqué par un immeuble récent.', NULL, true, 7, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('y-a-t-il-des-places-de-parking-reservees-aux-personnes-handi', 2, 'Y a-t-il des places de parking réservées aux personnes handicapées (PMR) ?', 'Oui.', NULL, true, 8, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('disposez-vous-d-un-parking-pour-les-patients', 2, 'Disposez-vous d''un parking pour les patients ?', 'Oui.', NULL, true, 9, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-transports-en-commun-desservent-votre-centre', 2, 'Quels transports en commun desservent votre centre ?', 'Le centre est desservi par les lignes de bus locales.', NULL, true, 10, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelles-sont-les-heures-d-ouverture-de-votre-centre', 2, 'Quelles sont les heures d''ouverture de votre centre ?', 'Du lundi au vendredi de 08h30 à 12h30 et de 13h15 à 18h30.', NULL, true, 11, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelles-sont-les-heures-de-pause-ou-de-fermeture-pendant-la', 2, 'Quelles sont les heures de pause ou de fermeture pendant la journée ?', 'Fermeture de 12h30 à 13h15.', NULL, true, 12, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-horaires-de-disponibilite-telephonique-de-vos', 2, 'Quels sont les horaires de disponibilité téléphonique de vos secrétaires ?', 'Du lundi au vendredi de 09h00 à 12h00 et de 14h00 à 17h00.', NULL, true, 13, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-jours-ou-periodes-de-fermeture-reguliere', 2, 'Quels sont les jours ou périodes de fermeture régulière ?', 'Fermeture le samedi, le dimanche et les jours fériés.', NULL, true, 14, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quel-est-le-numero-de-telephone-de-votre-secretariat-de-radi', 2, 'Quel est le numéro de téléphone de votre secrétariat de radiologie ?', '09 97 41 55 91', NULL, true, 15, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quel-est-le-numero-de-telephone-et-l-adresse-email-pour-cont', 2, 'Quel est le numéro de téléphone et l''adresse email pour contacter un(e) responsable du service ?', 'Les coordonnées du responsable ne sont pas communiquées aux patients. Les réclamations peuvent être adressées par mail à contact@riva56.fr ou par courrier à l''attention de l''équipe de direction du RIVA — 11c rue du Dr Joseph Audic, 56000 Vannes.', NULL, true, 16, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-email-du-centre-pour-les-demandes-d-inf', 2, 'Quelle est l''adresse email du centre pour les demandes d''information générale ?', 'contact@riva56.fr', NULL, true, 17, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-email-du-centre-pour-les-demandes-de-rd', 2, 'Quelle est l''adresse email du centre pour les demandes de RDV d''examen ?', 'contact@riva56.fr', NULL, true, 18, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-email-du-centre-pour-l-envoi-par-le-pat', 2, 'Quelle est l''adresse email du centre pour l''envoi par le patient d''ordonnances d''examen ?', 'contact@riva56.fr', NULL, true, 19, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-la-prise-de-rendez-vous-en-ligne', 2, 'Proposez-vous la prise de rendez-vous en ligne ?', 'Oui, via le site www.radiologiemuzillac.com.', NULL, true, 20, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-un-rappel-ou-une-confirmation-de-rendez-vous-p', 2, 'Proposez-vous un rappel ou une confirmation de rendez-vous par SMS ou email ?', 'Oui, selon les modalités habituelles du cabinet.', NULL, true, 21, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('souhaitez-vous-accepter-les-nouveaux-patients-dans-lyraetalk', 2, 'Souhaitez-vous accepter les nouveaux patients dans LyraeTalk ?', 'Oui.', NULL, true, 22, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-une-liste-d-attente-ou-un-systeme-de-rappel-po', 2, 'Proposez-vous une liste d''attente ou un système de rappel pour remplacer les rendez-vous annulés ?', 'Oui, selon les disponibilités du planning.', NULL, true, 23, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('existe-t-il-des-frais-en-cas-d-annulation-tardive-ou-d-absen', 2, 'Existe-t-il des frais en cas d''annulation tardive ou d''absence au rendez-vous ?', 'Non.', NULL, true, 24, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('en-cas-d-indisponibilite-de-creneau-dans-votre-centre-vers-q', 2, 'En cas d''indisponibilité de créneau dans votre centre, vers quels autres centres proposez-vous d''orienter le patient ?', 'Orientation vers d''autres cabinets du groupe RIVA selon la nature de l''examen.', NULL, true, 25, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('est-il-possible-de-choisir-son-radiologue-pour-un-examen', 2, 'Est-il possible de choisir son radiologue pour un examen ?', 'Non.', NULL, true, 26, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-examens-que-vous-pratiquez-dans-votre-centre', 2, 'Quels sont les examens que vous pratiquez dans votre centre ?', 'Radiographie du crâne, des sinus, du cavum et des os propres du nez ; Panoramique dentaire et articulation temporo-mandibulaire (ATM) ; Radiographie thoracique et du gril costal ; Radiographie de l''abdomen sans préparation (ASP) ; Radiographie du bassin et des hanches ; Radiographies du rachis (cervical, dorsal, lombaire, complet, sacrum-coccyx) ; Radiographies des membres supérieurs (épaule, bras, coude, avant-bras, poignet, main, âge osseux) ; Radiographies des membres inférieurs (hanche, cuisse, genou, jambe, cheville, pied) ; Radiographie du squelette ; Échographie cervicale, thyroïdienne et des glandes salivaires ; Échographie mammaire et des parties molles ; Échographie abdominale et abdomino-pelvienne ; Échographie rénale et vésicale ; Échographie hépatique ; Échographie pelvienne, prostatique et testiculaire ; Échographie musculo-squelettique (épaule, coude, poignet, main, hanche, genou, cheville, pied) ; Échographie de la hanche du nourrisson (dépistage) ; Échographie musculaire et des tendons.', NULL, true, 27, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('votre-centre-assure-t-il-la-realisation-d-examens-en-urgence', 2, 'Votre centre assure-t-il la réalisation d''examens en urgence ?', 'Oui, sur demande par téléphone.', NULL, true, 28, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('en-cas-d-examen-demande-en-urgence-est-il-possible-de-se-pre', 2, 'En cas d''examen demandé en urgence, est-il possible de se présenter sans rendez-vous ?', 'Non, les urgences sont organisées par téléphone.', NULL, true, 29, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-des-examens-interventionnels', 2, 'Proposez-vous des examens interventionnels ?', 'Non.', NULL, true, 30, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('disposez-vous-d-un-irm-ouvert-ou-semi-ouvert-pour-les-patien', 2, 'Disposez-vous d''un IRM ouvert ou semi-ouvert pour les patients claustrophobes ?', 'Non, le centre ne dispose pas d''IRM.', NULL, true, 31, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('avez-vous-des-fiches-de-consignes-pratiques-pour-la-preparat', 2, 'Avez-vous des fiches de consignes pratiques pour la préparation aux examens ?', 'Oui, selon le type d''examen réalisé.', NULL, true, 32, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('combien-de-radiologues-exercent-dans-ce-centre', 2, 'Combien de radiologues exercent dans ce centre ?', 'Les radiologues exercent au sein du groupe RIVA.', NULL, true, 33, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('les-radiologues-sont-ils-surspecialises-par-domaine-d-imager', 2, 'Les radiologues sont-ils surspécialisés par domaine d''imagerie ?', 'Non.', NULL, true, 34, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('le-centre-dispose-t-il-d-un-service-d-imagerie-de-garde', 2, 'Le centre dispose-t-il d''un service d''imagerie de garde ?', 'Non.', NULL, true, 35, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-documents-doit-on-apporter-pour-un-examen', 2, 'Quels documents doit-on apporter pour un examen ?', 'Ordonnance, carte Vitale, anciens examens, documents liés à un accident du travail ou à une demande employeur le cas échéant.', NULL, true, 36, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('combien-de-temps-faut-il-attendre-pour-recevoir-les-resultat', 2, 'Combien de temps faut-il attendre pour recevoir les résultats ?', 'Les résultats sont accessibles en ligne via un serveur sécurisé.', NULL, true, 37, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-la-gravure-de-cd', 2, 'Proposez-vous la gravure de CD ?', 'Oui.', NULL, true, 38, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-l-impression-des-cliches-sur-film', 2, 'Proposez-vous l''impression des clichés sur film ?', 'Oui, sur demande.', NULL, true, 39, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('comment-acceder-aux-resultats-d-imagerie-sur-internet', 2, 'Comment accéder aux résultats d''imagerie sur internet ?', 'Via un serveur de diffusion sécurisé avec code ou QR Code.', NULL, true, 40, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('le-compte-rendu-de-l-examen-est-il-automatiquement-envoye-a', 2, 'Le compte-rendu de l''examen est-il automatiquement envoyé à mon médecin traitant ?', 'Oui, par messagerie sécurisée.', NULL, true, 41, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('comment-puis-je-recuperer-une-copie-de-mes-anciens-examens', 2, 'Comment puis-je récupérer une copie de mes anciens examens ?', 'Via le serveur de diffusion en ligne ou sur demande au secrétariat.', NULL, true, 42, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('votre-centre-propose-t-il-du-wi-fi-pour-les-patients', 2, 'Votre centre propose-t-il du Wi-Fi pour les patients ?', 'Non.', NULL, true, 43, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('disposez-vous-d-une-salle-d-attente-adaptee-aux-enfants', 2, 'Disposez-vous d''une salle d''attente adaptée aux enfants ?', 'Non spécifiquement.', NULL, true, 44, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-vos-modes-de-paiement-acceptes', 2, 'Quels sont vos modes de paiement acceptés ?', 'Carte bancaire, chèque et espèces (espèces à éviter).', NULL, true, 45, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('pratiquez-vous-le-tiers-payant', 2, 'Pratiquez-vous le tiers payant ?', 'Oui, selon les conditions en vigueur.', NULL, true, 46, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('existe-t-il-des-depassements-d-honoraires-dans-votre-centre', 2, 'Existe-t-il des dépassements d''honoraires dans votre centre ?', 'Non, les radiologues exercent en secteur 1.', NULL, true, 47, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-moyens-pour-deposer-une-reclamation', 2, 'Quels sont les moyens pour déposer une réclamation ?', 'Par mail à contact@riva56.fr ou par courrier à l''attention de l''équipe de direction du RIVA — 11c rue du Dr Joseph Audic, 56000 Vannes.', NULL, true, 48, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
-- 49 items generes pour userProductId=2

-- ---------------------------------------------------------------------------
-- Centre userProductId=12 (A04.json)
-- ---------------------------------------------------------------------------
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quel-est-le-nom-complet-de-votre-centre-2', 12, 'Quel est le nom complet de votre centre ?', 'SELAS TESLA', NULL, true, 0, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-complete-de-votre-centre-2', 12, 'Quelle est l''adresse complète de votre centre ?', '71 avenue d''Angoulême, 16100 Châteaubernard', NULL, true, 1, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('votre-centre-possede-t-il-un-site-web-et-si-oui-quel-est-s-2', 12, 'Votre centre possède-t-il un site web et, si oui, quel est son lien ?', 'Oui, www.radiologiecognac.com', NULL, true, 2, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelles-sont-les-modalites-d-acces-a-votre-centre-entree-p-2', 12, 'Quelles sont les modalités d''accès à votre centre (entrée principale, étage, interphone…) ?', 'Accès par l''entrée principale de la radiologie ou par l''entrée principale du pôle IRM/Scanner.', NULL, true, 3, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-entree-recommandez-vous-aux-personnes-a-mobilite-re-2', 12, 'Quelle entrée recommandez-vous aux personnes à mobilité réduite ?', 'Les deux entrées sont accessibles aux personnes à mobilité réduite.', NULL, true, 4, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-phrase-dites-vous-au-telephone-au-patient-pour-lui-3', 12, 'Quelle phrase dites-vous au téléphone au patient pour lui expliquer comment se rendre à votre centre ?', 'Le centre se situe au 71 avenue d''Angoulême à Châteaubernard. La radiologie se trouve dans l''aile droite de la polyclinique, au fond du parking, en suivant le fléchage ''Centre d''imagerie''.', NULL, true, 5, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-phrase-dites-vous-au-telephone-au-patient-pour-lui-4', 12, 'Quelle phrase dites-vous au téléphone au patient pour lui expliquer comment trouver l''entrée de votre centre ?', 'Le centre est situé dans l''aile droite de la polyclinique, derrière le laboratoire d''analyses, tout au bout du parking.', NULL, true, 6, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('existe-t-il-des-difficultes-particulieres-pour-acceder-a-v-2', 12, 'Existe-t-il des difficultés particulières pour accéder à votre centre ?', 'Le cabinet est situé tout au bout du parking, sur la droite, facilement identifiable par de grandes baies vitrées et une inscription bleue ''Centre d''imagerie médicale''.', NULL, true, 7, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('y-a-t-il-des-places-de-parking-reservees-aux-personnes-han-2', 12, 'Y a-t-il des places de parking réservées aux personnes handicapées (PMR) ?', 'Oui.', NULL, true, 8, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('disposez-vous-d-un-parking-pour-les-patients-2', 12, 'Disposez-vous d''un parking pour les patients ?', 'Oui.', NULL, true, 9, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-transports-en-commun-desservent-votre-centre-2', 12, 'Quels transports en commun desservent votre centre ?', 'Le centre est desservi par la ligne B ou par le bus, arrêt « Pôle Santé ».', NULL, true, 10, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelles-sont-les-heures-d-ouverture-de-votre-centre-2', 12, 'Quelles sont les heures d''ouverture de votre centre ?', 'Centre d''imagerie : du lundi au vendredi de 8h00 à 12h30 et de 14h00 à 18h00. Pôle IRM/Scanner : du lundi au vendredi de 8h00 à 18h00, et le samedi de 8h00 à 12h00.', NULL, true, 11, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelles-sont-les-heures-de-pause-ou-de-fermeture-pendant-l-2', 12, 'Quelles sont les heures de pause ou de fermeture pendant la journée ?', 'Le centre d''imagerie est fermé de 12h30 à 14h00. Le pôle IRM/Scanner fonctionne en journée continue.', NULL, true, 12, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-horaires-de-disponibilite-telephonique-de-v-2', 12, 'Quels sont les horaires de disponibilité téléphonique de vos secrétaires ?', 'Du lundi au vendredi de 8h00 à 12h30 et de 14h00 à 17h30.', NULL, true, 13, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-jours-ou-periodes-de-fermeture-reguliere-2', 12, 'Quels sont les jours ou périodes de fermeture régulière ?', 'Centre d''imagerie : fermé le samedi, le dimanche et les jours fériés. Pôle IRM/Scanner : fermé le samedi après 12h00, le dimanche et les jours fériés. Seuls les examens d''IRM sont réalisables le samedi.', NULL, true, 14, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quel-est-le-numero-de-telephone-de-votre-secretariat-de-ra-2', 12, 'Quel est le numéro de téléphone de votre secrétariat de radiologie ?', 'Ligne patients : 05 45 82 08 80. Ligne professionnels : 05 45 82 08 35.', NULL, true, 15, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quel-est-le-numero-de-telephone-et-l-adresse-email-pour-co-2', 12, 'Quel est le numéro de téléphone et l''adresse email pour contacter un(e) responsable du service ?', 'Téléphone : 05 45 35 68 96. Email : cadre@radiologie-cognac.com.', NULL, true, 16, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-email-du-centre-pour-les-demandes-d-i-2', 12, 'Quelle est l''adresse email du centre pour les demandes d''information générale ?', 'secretaire@radiologie-cognac.com', NULL, true, 17, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-email-du-centre-pour-les-demandes-de-2', 12, 'Quelle est l''adresse email du centre pour les demandes de RDV d''examen ?', 'secretaire@radiologie-cognac.com', NULL, true, 18, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-email-du-centre-pour-l-envoi-par-le-p-2', 12, 'Quelle est l''adresse email du centre pour l''envoi par le patient d''ordonnances d''examen ?', 'secretaire@radiologie-cognac.com', NULL, true, 19, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-la-prise-de-rendez-vous-en-ligne-2', 12, 'Proposez-vous la prise de rendez-vous en ligne ?', 'Oui.', NULL, true, 20, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-un-rappel-ou-une-confirmation-de-rendez-vous-2', 12, 'Proposez-vous un rappel ou une confirmation de rendez-vous par SMS ou email ?', 'Oui, par SMS et par email.', NULL, true, 21, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('souhaitez-vous-accepter-les-nouveaux-patients-dans-lyraeta-2', 12, 'Souhaitez-vous accepter les nouveaux patients dans LyraeTalk ?', 'Oui.', NULL, true, 22, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-une-liste-d-attente-ou-un-systeme-de-rappel-2', 12, 'Proposez-vous une liste d''attente ou un système de rappel pour remplacer les rendez-vous annulés ?', 'Oui, une liste d''attente est proposée et renseignée au moment de la prise de rendez-vous.', NULL, true, 23, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('existe-t-il-des-frais-en-cas-d-annulation-tardive-ou-d-abs-2', 12, 'Existe-t-il des frais en cas d''annulation tardive ou d''absence au rendez-vous ?', 'Non.', NULL, true, 24, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('en-cas-d-indisponibilite-de-creneau-dans-votre-centre-vers-2', 12, 'En cas d''indisponibilité de créneau dans votre centre, vers quels autres centres proposez-vous d''orienter le patient ?', 'Nous orientons vers le centre de radiologie du centre hospitalier de Cognac.', NULL, true, 25, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('est-il-possible-de-choisir-son-radiologue-pour-un-examen-2', 12, 'Est-il possible de choisir son radiologue pour un examen ?', 'Non.', NULL, true, 26, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-examens-que-vous-pratiquez-dans-votre-centr-2', 12, 'Quels sont les examens que vous pratiquez dans votre centre ?', 'Radiographie, échographie, doppler artériel, mammographie, ostéodensitométrie, panoramique dentaire, scanner, IRM.', NULL, true, 27, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('combien-de-temps-en-moyenne-le-patient-va-t-il-passer-sur-pl', 12, 'Combien de temps en moyenne le patient va-t-il passer sur place pour chaque examen ?', 'Radiographie : 30 min ; échographie : 45 min ; radio + écho : 1 h ; mammographie : 30 min ; ostéodensitométrie : 45 min ; panoramique dentaire : 30 min ; scanner : 30 min ; IRM : 45 min ; examens interventionnels : 1 h.', NULL, true, 28, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('votre-centre-assure-t-il-la-realisation-d-examens-en-urgen-2', 12, 'Votre centre assure-t-il la réalisation d''examens en urgence ?', 'Oui, pour la radiographie, l''échographie, la mammographie et le scanner.', NULL, true, 29, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('en-cas-d-examen-demande-en-urgence-est-il-possible-de-se-p-2', 12, 'En cas d''examen demandé en urgence, est-il possible de se présenter sans rendez-vous ?', 'Non. Les urgences sont organisées sur demande d''un médecin traitant ou d''un chirurgien de la polyclinique, qui obtient un rendez-vous sur place.', NULL, true, 30, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-des-examens-interventionnels-2', 12, 'Proposez-vous des examens interventionnels ?', 'Oui : infiltrations sous radiographie, échographie ou scanner (lombaire uniquement), biopsie mammaire, ponctions thyroïdiennes, mammaires, kystiques ou d''hématomes, PRP et viscosupplémentations.', NULL, true, 31, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('disposez-vous-d-un-irm-ouvert-ou-semi-ouvert-pour-les-pati-2', 12, 'Disposez-vous d''un IRM ouvert ou semi-ouvert pour les patients claustrophobes ?', 'Non, mais l''IRM dispose d''une ouverture large de 70 cm.', NULL, true, 32, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('avez-vous-des-fiches-de-consignes-pratiques-pour-la-prepar-2', 12, 'Avez-vous des fiches de consignes pratiques pour la préparation aux examens ?', 'Oui, disponibles en annexe.', NULL, true, 33, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('combien-de-radiologues-exercent-dans-ce-centre-2', 12, 'Combien de radiologues exercent dans ce centre ?', 'Un seul radiologue exerce dans ce centre.', NULL, true, 34, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-radiologues-qui-exercent-dans-votre-centre', 12, 'Quels sont les radiologues qui exercent dans votre centre ?', 'Dr Morales Pierrick.', NULL, true, 35, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('les-radiologues-sont-ils-surspecialises-par-domaine-d-imag-2', 12, 'Les radiologues sont-ils surspécialisés par domaine d''imagerie ?', 'Non.', NULL, true, 36, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('le-centre-dispose-t-il-d-un-service-d-imagerie-de-garde-2', 12, 'Le centre dispose-t-il d''un service d''imagerie de garde ?', 'Non.', NULL, true, 37, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-documents-doit-on-apporter-pour-un-examen-2', 12, 'Quels documents doit-on apporter pour un examen ?', 'Ordonnance, carte Vitale ou attestation, mutuelle, pièce d''identité, documents liés à un accident du travail si nécessaire. Pour scanner, IRM et mammographie : apporter les examens antérieurs.', NULL, true, 38, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('combien-de-temps-faut-il-attendre-pour-recevoir-les-result-2', 12, 'Combien de temps faut-il attendre pour recevoir les résultats ?', 'Entre 24 et 48 heures.', NULL, true, 39, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-la-gravure-de-cd-2', 12, 'Proposez-vous la gravure de CD ?', 'Oui.', NULL, true, 40, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-l-impression-des-cliches-sur-film-2', 12, 'Proposez-vous l''impression des clichés sur film ?', 'Oui.', NULL, true, 41, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('comment-acceder-aux-resultats-d-imagerie-sur-internet-2', 12, 'Comment accéder aux résultats d''imagerie sur internet ?', 'Via la plateforme de Web Diffusion.', NULL, true, 42, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('le-compte-rendu-de-l-examen-est-il-automatiquement-envoye-2', 12, 'Le compte-rendu de l''examen est-il automatiquement envoyé à mon médecin traitant ?', 'Oui, si son adresse MS Santé a été renseignée.', NULL, true, 43, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('comment-puis-je-recuperer-une-copie-de-mes-anciens-examens-2', 12, 'Comment puis-je récupérer une copie de mes anciens examens ?', 'Sur demande par email à secretaire@radiologie-cognac.com. Les examens seront mis à disposition via la Web Diffusion.', NULL, true, 44, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('est-il-possible-que-les-images-soient-envoyees-directement-a', 12, 'Est-il possible que les images soient envoyées directement à un autre spécialiste si besoin ?', 'Oui, sur demande écrite.', NULL, true, 45, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('votre-centre-propose-t-il-du-wi-fi-pour-les-patients-2', 12, 'Votre centre propose-t-il du Wi-Fi pour les patients ?', 'Non.', NULL, true, 46, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('disposez-vous-d-une-salle-d-attente-adaptee-aux-enfants-2', 12, 'Disposez-vous d''une salle d''attente adaptée aux enfants ?', 'Non.', NULL, true, 47, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-vos-modes-de-paiement-acceptes-2', 12, 'Quels sont vos modes de paiement acceptés ?', 'Espèces, carte bancaire et chèque.', NULL, true, 48, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('pratiquez-vous-le-tiers-payant-2', 12, 'Pratiquez-vous le tiers payant ?', 'Oui.', NULL, true, 49, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('existe-t-il-des-depassements-d-honoraires-dans-votre-centr-2', 12, 'Existe-t-il des dépassements d''honoraires dans votre centre ?', 'Oui, pour les examens suivants : les infiltrations sous radio ou échographie, les infiltrations sous scanner, les viscosupplémentations, les PRP.', NULL, true, 50, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-montants-des-depassements-d-honoraires-applic', 12, 'Quels sont les montants des dépassements d''honoraires applicables ?', 'Les montants des dépassements d''honoraires applicables sont : 15 € pour les infiltrations sous radio ou échographie, 50 € pour les infiltrations sous scanner, 70 € pour les viscosupplémentations, 150 € pour les PRP.', NULL, true, 51, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-moyens-pour-deposer-une-reclamation-2', 12, 'Quels sont les moyens pour déposer une réclamation ?', 'Par email à secretaire@radiologie-cognac.com ou par courrier à : SELAS TESLA, 71 avenue d''Angoulême, 16100 Châteaubernard.', NULL, true, 52, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
-- 53 items generes pour userProductId=12

-- ---------------------------------------------------------------------------
-- Centre userProductId=15 (MEN.json)
-- ---------------------------------------------------------------------------
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quel-est-le-nom-complet-de-votre-centre-3', 15, 'Quel est le nom complet de votre centre ?', 'Le centre s''appelle Centre Hospitalier La Palmosa, situé à Menton.', NULL, true, 0, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-complete-de-votre-centre-3', 15, 'Quelle est l''adresse complète de votre centre ?', 'Le centre est situé au 2 rue Antoine Péglion, 06500 Menton. Il s''agit du Centre Hospitalier de Menton.', NULL, true, 1, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('votre-centre-possede-t-il-un-site-web-et-si-oui-quel-est-s-3', 15, 'Votre centre possède-t-il un site web et, si oui, quel est son lien ?', 'Oui, le centre dispose d''un site web officiel accessible à l''adresse suivante : https://ch-menton.fr/.', NULL, true, 2, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelles-sont-les-modalites-d-acces-a-votre-centre-entree-p-3', 15, 'Quelles sont les modalités d''accès à votre centre (entrée principale, étage, interphone…) ?', 'L''accès au service est fléché et structuré dès le hall d''accueil de l''hôpital. À votre arrivée, veuillez vous enregistrer via la borne d''accueil en prenant un ticket.', NULL, true, 3, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-phrase-dites-vous-au-telephone-au-patient-pour-lui-5', 15, 'Quelle phrase dites-vous au téléphone au patient pour lui expliquer comment trouver l''entrée de votre centre ?', 'À votre arrivée dans le hall principal de l''hôpital, suivez la signalétique jusqu''au service. Merci de vous enregistrer à la borne d''accueil en prenant un ticket.', NULL, true, 4, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('existe-t-il-des-difficultes-particulieres-pour-acceder-a-v-3', 15, 'Existe-t-il des difficultés particulières pour accéder à votre centre ?', 'Non, il n''existe aucune difficulté particulière signalée pour accéder au centre.', NULL, true, 5, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('y-a-t-il-des-places-de-parking-reservees-aux-personnes-han-3', 15, 'Y a-t-il des places de parking réservées aux personnes handicapées (PMR) ?', 'Oui, des places de stationnement réservées aux personnes à mobilité réduite (PMR) sont disponibles directement devant l''entrée principale du centre, facilitant ainsi l''accès aux patients en situation de handicap.', NULL, true, 6, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('disposez-vous-d-un-parking-pour-les-patients-3', 15, 'Disposez-vous d''un parking pour les patients ?', 'Pas de parking à l''hôpital, prévoir de se garer dans les rues proches payantes.', NULL, true, 7, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-transports-en-commun-desservent-votre-centre-3', 15, 'Quels transports en commun desservent votre centre ?', 'L''hôpital est desservi par trois arrêts de bus à proximité : Pagnol Hôpital La Palmosa, Hôpital, et Maison Russe.', NULL, true, 8, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-examens-realisables-le-samedi', 15, 'Quels sont les examens réalisables le samedi ?', 'Des rendez-vous sont possibles le samedi matin uniquement pour les IRM du genou et les IRM lombaires. La prise de rendez-vous se fait exclusivement via le secrétariat (pas de réservation en ligne ni via le robot).', NULL, true, 9, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelles-sont-les-heures-d-ouverture-de-votre-centre-3', 15, 'Quelles sont les heures d''ouverture de votre centre ?', 'L''hôpital est ouvert 24 heures sur 24, 7 jours sur 7, sans aucune pause ni fermeture en cours de journée, et sans jours de fermeture régulière. Il assure une continuité de service permanente tout au long de l''année.', NULL, true, 10, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelles-sont-les-heures-de-pause-ou-de-fermeture-pendant-l-3', 15, 'Quelles sont les heures de pause ou de fermeture pendant la journée ?', 'Il n''existe aucune heure de pause ni de fermeture pendant la journée. L''hôpital est ouvert en continu 24h/24.', NULL, true, 11, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-horaires-de-disponibilite-telephonique-de-v-3', 15, 'Quels sont les horaires de disponibilité téléphonique de vos secrétaires ?', 'Les secrétaires du service imagerie de l''hôpital sont joignables par téléphone du lundi au vendredi, de 08h00 à 18h00.', NULL, true, 12, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-jours-ou-periodes-de-fermeture-reguliere-3', 15, 'Quels sont les jours ou périodes de fermeture régulière ?', 'Il n''existe aucun jour ni aucune période de fermeture régulière. Le centre est ouvert toute l''année, y compris les jours fériés.', NULL, true, 13, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quel-est-le-numero-de-telephone-de-votre-secretariat-de-ra-3', 15, 'Quel est le numéro de téléphone de votre secrétariat de radiologie ?', 'Le numéro de téléphone du secrétariat de radiologie est le 04 93 28 72 32.', NULL, true, 14, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quel-est-le-numero-de-telephone-et-l-adresse-email-pour-co-3', 15, 'Quel est le numéro de téléphone et l''adresse email pour contacter un(e) responsable du service ?', 'secretariat.radiologie@ch-menton.fr', NULL, true, 15, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-email-du-centre-pour-les-demandes-d-i-3', 15, 'Quelle est l''adresse email du centre pour les demandes d''information générale ?', 'secretariat.radiologie@ch-menton.fr', NULL, true, 16, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-email-du-centre-pour-les-demandes-de-3', 15, 'Quelle est l''adresse email du centre pour les demandes de RDV d''examen ?', 'secretariat.radiologie@ch-menton.fr', NULL, true, 17, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-email-du-centre-pour-l-envoi-par-le-p-3', 15, 'Quelle est l''adresse email du centre pour l''envoi par le patient d''ordonnances d''examen ?', 'secretariat.radiologie@ch-menton.fr', NULL, true, 18, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-la-prise-de-rendez-vous-en-ligne-3', 15, 'Proposez-vous la prise de rendez-vous en ligne ?', 'Oui, la prise de rendez-vous en ligne est disponible directement sur le site officiel du centre : ch-menton.fr ou bien sur Doctolib.', NULL, true, 19, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-un-rappel-ou-une-confirmation-de-rendez-vous-3', 15, 'Proposez-vous un rappel ou une confirmation de rendez-vous par SMS ou email ?', 'Un SMS est envoyé 3 jours avant le rendez-vous avec un rappel, les consignes à suivre et les documents nécessaires.', NULL, true, 20, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('souhaitez-vous-accepter-les-nouveaux-patients-dans-lyraeta-3', 15, 'Souhaitez-vous accepter les nouveaux patients dans LyraeTalk ?', 'Oui.', NULL, true, 21, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-une-liste-d-attente-ou-un-systeme-de-rappel-3', 15, 'Proposez-vous une liste d''attente ou un système de rappel pour remplacer les rendez-vous annulés ?', 'Non.', NULL, true, 22, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('existe-t-il-des-frais-en-cas-d-annulation-tardive-ou-d-abs-3', 15, 'Existe-t-il des frais en cas d''annulation tardive ou d''absence au rendez-vous ?', 'Non, pas de frais en cas d''annulation tardive ou d''absence au rendez-vous.', NULL, true, 23, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-examens-que-vous-pratiquez-dans-votre-centr-3', 15, 'Quels sont les examens que vous pratiquez dans votre centre ?', 'Radiographie, échographie, doppler / écho-doppler, mammographie, scanner et IRM.', NULL, true, 24, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('combien-de-temps-en-moyenne-le-patient-va-t-il-passer-sur-2', 15, 'Combien de temps en moyenne le patient va-t-il passer sur place pour chaque examen ?', 'Entre 30 et 60 minutes.', NULL, true, 25, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('votre-centre-assure-t-il-la-realisation-d-examens-en-urgen-3', 15, 'Votre centre assure-t-il la réalisation d''examens en urgence ?', 'Oui, les examens en urgence sont pris en charge uniquement via le service des urgences.', NULL, true, 26, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('en-cas-d-examen-demande-en-urgence-est-il-possible-de-se-p-3', 15, 'En cas d''examen demandé en urgence, est-il possible de se présenter sans rendez-vous ?', 'Non, les consultations sans rendez-vous ne sont pas possibles, sauf en passant par le service des urgences.', NULL, true, 27, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('en-cas-d-urgence-medicale-quelle-consigne-donnez-vous-lors-d', 15, 'En cas d''urgence médicale, quelle consigne donnez-vous lors de la fermeture du secrétariat ?', 'En cas d''urgence vitale pendant la fermeture du secrétariat, il est demandé d''appeler le 15.', NULL, true, 28, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('les-radiologues-sont-ils-surspecialises-par-domaine-d-imag-3', 15, 'Les radiologues sont-ils surspécialisés par domaine d''imagerie ?', 'Oui, les radiologues interviennent par domaines de spécialisation, notamment en urologie (prostate), en neurologie et en gynécologie/pelvis.', NULL, true, 29, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('le-centre-dispose-t-il-d-un-service-d-imagerie-de-garde-3', 15, 'Le centre dispose-t-il d''un service d''imagerie de garde ?', 'Oui, le centre dispose du service de garde qui est réservé uniquement au service des urgences.', NULL, true, 30, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-documents-doit-on-apporter-pour-un-examen-3', 15, 'Quels documents doit-on apporter pour un examen ?', 'Carte vitale, mutuelle, attestation d''assurance maladie si la carte vitale est absente, ordonnance, anciens examens concernant le problème en cours, et mode de paiement (chèque, carte bleue, espèces).', NULL, true, 31, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('comment-acceder-aux-resultats-d-imagerie-sur-internet-3', 15, 'Comment accéder aux résultats d''imagerie sur internet ?', 'Un code d''accès est remis le jour de l''examen par la secrétaire, permettant de consulter les résultats en ligne.', NULL, true, 32, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('le-compte-rendu-de-l-examen-est-il-automatiquement-envoye-3', 15, 'Le compte-rendu de l''examen est-il automatiquement envoyé à mon médecin traitant ?', 'Oui, le compte rendu est envoyé au médecin prescripteur (traitant).', NULL, true, 33, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('comment-puis-je-recuperer-une-copie-de-mes-anciens-examens-3', 15, 'Comment puis-je récupérer une copie de mes anciens examens ?', 'La demande peut être effectuée par e-mail ou directement sur place. Une facturation peut s''appliquer.', NULL, true, 34, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('est-il-possible-que-les-images-soient-envoyees-directement-2', 15, 'Est-il possible que les images soient envoyées directement à un autre spécialiste si besoin ?', 'Oui, la transmission des résultats d''examen est possible, mais uniquement vers les hôpitaux publics des Alpes-Maritimes.', NULL, true, 35, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('votre-centre-propose-t-il-du-wi-fi-pour-les-patients-3', 15, 'Votre centre propose-t-il du Wi-Fi pour les patients ?', 'Oui.', NULL, true, 36, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('disposez-vous-d-une-salle-d-attente-adaptee-aux-enfants-3', 15, 'Disposez-vous d''une salle d''attente adaptée aux enfants ?', 'Non.', NULL, true, 37, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-vos-modes-de-paiement-acceptes-3', 15, 'Quels sont vos modes de paiement acceptés ?', 'Espèces, carte bancaire et chèque.', NULL, true, 38, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('pratiquez-vous-le-tiers-payant-3', 15, 'Pratiquez-vous le tiers payant ?', 'Le tiers payant est pratiqué, mais uniquement avec les complémentaires santé ayant signé un accord préalable avec le centre. Il est conseillé de se renseigner directement à l''accueil avant votre venue pour vérifier si votre mutuelle est concernée.', NULL, true, 39, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('existe-t-il-des-depassements-d-honoraires-dans-votre-centr-3', 15, 'Existe-t-il des dépassements d''honoraires dans votre centre ?', 'Oui, des dépassements d''honoraires s''appliquent sur certains actes spécifiques : les infiltrations et ponctions sous échographie et sous radiographie, les biopsies, ainsi que les échographies et mammographies réalisées par les radiologues exerçant en secteur 2.', NULL, true, 40, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-montants-des-depassements-d-honoraires-appl-2', 15, 'Quels sont les montants des dépassements d''honoraires applicables ?', 'Les dépassements d''honoraires sont les suivants : 40 € pour les infiltrations et ponctions sous échographie, 50 € pour les infiltrations et ponctions sous radiographie, 50 € pour les biopsies. Pour les radiologues exerçant en secteur 2 : 30 € pour les échographies et 30 € pour les mammographies.', NULL, true, 41, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-moyens-pour-deposer-une-reclamation-3', 15, 'Quels sont les moyens pour déposer une réclamation ?', 'Mail, courrier, téléphone.', NULL, true, 42, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
-- 43 items generes pour userProductId=15

-- Bump moduleInfoVersion pour les 3 centres
UPDATE "UserProduct" SET "moduleInfoVersion" = NOW() WHERE "id" = 2;
UPDATE "UserProduct" SET "moduleInfoVersion" = NOW() WHERE "id" = 12;
UPDATE "UserProduct" SET "moduleInfoVersion" = NOW() WHERE "id" = 15;

COMMIT;

-- TOTAL : 145 items inseres (hors items skippes pour reponse vide)
