-- =============================================================================
-- Seed ModuleInfoItem : FAQ patient RIM29 SUD + GHCB (chantier 2026-08-06 v2)
-- =============================================================================
--
-- Import initial des Q/R FAQ patient pour 4 nouveaux centres :
--   - userProductId=18 -> RIM29 SUD Quimper (QUIMPER.json)
--   - userProductId=20 -> RIM29 SUD Fouesnant (FOUESNANT.json)
--   - userProductId=21 -> RIM29 SUD Pont-l'Abbe (PONT-L-ABBE.json)
--   - userProductId=22 -> GHCB Pontivy (PONTIVY.json)
--
-- Slugs uniques GLOBALEMENT (PK Postgres est globale a la table). Le set
-- de dedup est pre-initialise avec les slugs du seed precedent (centres
-- 2/12/15) charges depuis 2026_08_06_seed_module_info_3_centres.sql pour
-- eviter les collisions inter-centres.
--
-- Idempotent : ON CONFLICT (id) DO NOTHING + bump moduleInfoVersion.
-- =============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- Centre userProductId=18 (QUIMPER.json)
-- ---------------------------------------------------------------------------
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quel-est-le-nom-complet-de-votre-centre-4', 18, 'Quel est le nom complet de votre centre ?', 'RIM29 SUD – Réseau d''Imagerie Médicale 29 Sud – site de Quimper (siège)', NULL, true, 0, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-complete-de-votre-centre-4', 18, 'Quelle est l''adresse complète de votre centre ?', '11 chemin de Penhoat – 29000 Quimper', NULL, true, 1, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('votre-centre-possede-t-il-un-site-web-et-si-oui-quel-est-s-4', 18, 'Votre centre possède-t-il un site web et, si oui, quel est son lien ?', 'Oui, https://www.rim29sud.fr/', NULL, true, 2, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelles-sont-les-modalites-d-acces-a-votre-centre-entree-p-4', 18, 'Quelles sont les modalités d''accès à votre centre (entrée principale, étage, interphone…) ?', 'Accès par la porte 2.', NULL, true, 3, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-entree-recommandez-vous-aux-personnes-a-mobilite-re-3', 18, 'Quelle entrée recommandez-vous aux personnes à mobilité réduite ?', 'Accès PMR avec parking réservé. Pour les patients en brancard, l''accès s''effectue avec les ambulanciers par l''arrière du bâtiment, via l''entrée des soins non programmés.', NULL, true, 4, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-phrase-dites-vous-au-telephone-au-patient-pour-lui-6', 18, 'Quelle phrase dites-vous au téléphone au patient pour lui expliquer comment se rendre à votre centre ?', 'Le centre se situe au 11 chemin de Penhoat, 29000 Quimper. Depuis le centre-ville, prenez la D783 en direction de Penhoat, puis tournez à gauche sur le chemin de Penhoat.', NULL, true, 5, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-phrase-dites-vous-au-telephone-au-patient-pour-lui-7', 18, 'Quelle phrase dites-vous au téléphone au patient pour lui expliquer comment trouver l''entrée de votre centre ?', 'Le cabinet se situe porte 2, entre la maison médicale et la Clinique Mutualiste.', NULL, true, 6, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('existe-t-il-des-difficultes-particulieres-pour-acceder-a-v-4', 18, 'Existe-t-il des difficultés particulières pour accéder à votre centre ?', 'Non.', NULL, true, 7, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('y-a-t-il-des-places-de-parking-reservees-aux-personnes-han-4', 18, 'Y a-t-il des places de parking réservées aux personnes handicapées (PMR) ?', 'Oui, sur les 3 sites.', NULL, true, 8, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('disposez-vous-d-un-parking-pour-les-patients-4', 18, 'Disposez-vous d''un parking pour les patients ?', 'Oui, sur les 3 sites.', NULL, true, 9, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-transports-en-commun-desservent-votre-centre-4', 18, 'Quels transports en commun desservent votre centre ?', 'Ligne de bus n°9.', NULL, true, 10, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelles-sont-les-heures-d-ouverture-de-votre-centre-4', 18, 'Quelles sont les heures d''ouverture de votre centre ?', 'Du lundi au vendredi de 8h00 à 18h30, le samedi de 8h00 à 12h30.', NULL, true, 11, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelles-sont-les-heures-de-pause-ou-de-fermeture-pendant-l-4', 18, 'Quelles sont les heures de pause ou de fermeture pendant la journée ?', 'Aucune : le site fonctionne en journée continue.', NULL, true, 12, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-horaires-de-disponibilite-telephonique-de-v-4', 18, 'Quels sont les horaires de disponibilité téléphonique de vos secrétaires ?', 'Du lundi au vendredi de 8h00 à 18h30, le samedi de 8h00 à 12h30.', NULL, true, 13, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-jours-ou-periodes-de-fermeture-reguliere-4', 18, 'Quels sont les jours ou périodes de fermeture régulière ?', 'Fermeture du samedi 12h30 au lundi 8h00, ainsi que les jours fériés.', NULL, true, 14, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quel-est-le-numero-de-telephone-de-votre-secretariat-de-ra-4', 18, 'Quel est le numéro de téléphone de votre secrétariat de radiologie ?', '02 98 95 21 21', NULL, true, 15, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quel-est-le-numero-de-telephone-et-l-adresse-email-pour-co-4', 18, 'Quel est le numéro de téléphone et l''adresse email pour contacter un(e) responsable du service ?', 'Isabelle Quentel-Gourves (Responsable centre d''appels) : 02 72 88 28 42 – iquentelgourves@29sud.fr
Coat Christelle (Directrice) : 02 72 88 28 41 – ccoat@29sud.fr', NULL, true, 16, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-email-du-centre-pour-les-demandes-d-i-4', 18, 'Quelle est l''adresse email du centre pour les demandes d''information générale ?', 'contact@29sud.fr', NULL, true, 17, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-email-du-centre-pour-les-demandes-de-4', 18, 'Quelle est l''adresse email du centre pour les demandes de RDV d''examen ?', 'contact@29sud.fr', NULL, true, 18, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-email-du-centre-pour-l-envoi-par-le-p-4', 18, 'Quelle est l''adresse email du centre pour l''envoi par le patient d''ordonnances d''examen ?', 'ordo@29sud.fr (uniquement lorsqu''un rendez-vous a déjà été posé ; une réponse automatique confirme la bonne réception des documents).', NULL, true, 19, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-la-prise-de-rendez-vous-en-ligne-4', 18, 'Proposez-vous la prise de rendez-vous en ligne ?', 'Oui, via Radiobooking : https://www.rim29sud.fr/infos-rdv.html', NULL, true, 20, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-un-rappel-ou-une-confirmation-de-rendez-vous-4', 18, 'Proposez-vous un rappel ou une confirmation de rendez-vous par SMS ou email ?', 'Oui. Via Radiobooking : rappel par SMS et email. Le centre d''appels envoie également des SMS de confirmation pour tous les examens, sauf les radiographies standards où seul un rappel est transmis 24h avant le rendez-vous. Les infiltrations sous échographie ne donnent pas lieu à l''envoi de SMS.', NULL, true, 21, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('souhaitez-vous-accepter-les-nouveaux-patients-dans-lyraeta-4', 18, 'Souhaitez-vous accepter les nouveaux patients dans LyraeTalk ?', 'Non renseigné.', NULL, true, 22, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-une-liste-d-attente-ou-un-systeme-de-rappel-4', 18, 'Proposez-vous une liste d''attente ou un système de rappel pour remplacer les rendez-vous annulés ?', 'Oui. En cas d''annulation, les patients souhaitant être rappelés sont contactés par téléphone. Le rendez-vous est attribué au premier patient joignable et disponible. Aucun message vocal n''est laissé.', NULL, true, 23, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('existe-t-il-des-frais-en-cas-d-annulation-tardive-ou-d-abs-4', 18, 'Existe-t-il des frais en cas d''annulation tardive ou d''absence au rendez-vous ?', 'Non.', NULL, true, 24, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('en-cas-d-indisponibilite-de-creneau-dans-votre-centre-vers-3', 18, 'En cas d''indisponibilité de créneau dans votre centre, vers quels autres centres proposez-vous d''orienter le patient ?', 'Le réseau dispose de 3 sites (Quimper, Fouesnant, Pont-l''Abbé) et a généralement des disponibilités pour les examens courants (radiographie, échographie, mammographie). Les patients ne sont pas orientés vers d''autres structures.', NULL, true, 25, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('est-il-possible-de-choisir-son-radiologue-pour-un-examen-3', 18, 'Est-il possible de choisir son radiologue pour un examen ?', 'Pour les radiographies, les examens sont répartis aléatoirement entre les radiologues : il n''est pas possible de garantir quel praticien interprétera l''examen. Pour les IRM, scanners, échographies et mammographies, le choix du radiologue reste possible selon les disponibilités des plannings.', NULL, true, 26, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-examens-que-vous-pratiquez-dans-votre-centr-4', 18, 'Quels sont les examens que vous pratiquez dans votre centre ?', 'EOS, radiographie, mammographie, ostéodensitométrie, échographie, échodoppler (Dr Rohou uniquement), IRM, scanner.', NULL, true, 27, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('combien-de-temps-en-moyenne-le-patient-va-t-il-passer-sur-3', 18, 'Combien de temps en moyenne le patient va-t-il passer sur place pour chaque examen ?', 'Radiographie : environ 1h ; ostéodensitométrie : environ 1h ; échographie : environ 1h ; EOS : environ 1h ; mammographie : environ 1h ; IRM : entre 1h et 2h ; scanner : entre 1h et 2h.', NULL, true, 28, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('votre-centre-assure-t-il-la-realisation-d-examens-en-urgen-4', 18, 'Votre centre assure-t-il la réalisation d''examens en urgence ?', 'Oui, uniquement sur rendez-vous. Une salle est dédiée aux urgences radiographiques (RX3). Des créneaux sont également réservés en échographie, mammographie, scanner et IRM. Aucune urgence n''est réalisée en ostéodensitométrie.', NULL, true, 29, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('en-cas-d-examen-demande-en-urgence-est-il-possible-de-se-p-4', 18, 'En cas d''examen demandé en urgence, est-il possible de se présenter sans rendez-vous ?', 'Non, tous les examens sont réalisés uniquement sur rendez-vous.', NULL, true, 30, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('en-cas-d-urgence-medicale-quelle-consigne-donnez-vous-lors-2', 18, 'En cas d''urgence médicale, quelle consigne donnez-vous lors de la fermeture du secrétariat ?', 'En cas d''urgence vitale, appeler le 15. Sinon, se rapprocher de son médecin traitant.', NULL, true, 31, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-des-examens-interventionnels-3', 18, 'Proposez-vous des examens interventionnels ?', 'Oui, mais ces rendez-vous ne sont pas pris en charge par LyraeTalk. Un circuit dédié existe via la file d''attente n°3 du SVI.', NULL, true, 32, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('disposez-vous-d-un-irm-ouvert-ou-semi-ouvert-pour-les-pati-3', 18, 'Disposez-vous d''un IRM ouvert ou semi-ouvert pour les patients claustrophobes ?', 'Oui, le site dispose d''un IRM adapté. Une prémédication peut être prescrite en cas de claustrophobie.', NULL, true, 33, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('avez-vous-des-fiches-de-consignes-pratiques-pour-la-prepar-3', 18, 'Avez-vous des fiches de consignes pratiques pour la préparation aux examens ?', 'Oui. Toutes les consignes sont données lors de la prise de rendez-vous et une fiche de consignes est expédiée au patient en fonction de l''examen.', NULL, true, 34, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('combien-de-radiologues-exercent-dans-ce-centre-3', 18, 'Combien de radiologues exercent dans ce centre ?', '14 radiologues et 3 manipulateurs échographes pour l''ensemble du réseau (3 sites).', NULL, true, 35, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-radiologues-qui-exercent-dans-votre-centre-2', 18, 'Quels sont les radiologues qui exercent dans votre centre ?', 'Radiologues résidents : Dr Bertevas-Galliou Geneviève, Dr Auter-Gestin Hervé, Dr Jaouen Alexandre, Dr Kervennic Pascal, Dr Kollo Ali, Dr Perdriel Benoit, Dr Prigent Luc, Dr Rohou Tanguy (secteur 2), Dr Texier Franck.
Radiologues vacataires : Dr Le Bihan Eric, Dr Meneux Baptiste, Dr Helias Laurent, Dr De Kermerchou, Dr Ogoundele Modeste.
Manipulateurs échographes : Albrecht Isabelle, Marchal François, Olivry Christelle.', NULL, true, 36, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('les-radiologues-sont-ils-surspecialises-par-domaine-d-imag-4', 18, 'Les radiologues sont-ils surspécialisés par domaine d''imagerie ?', 'Oui. Drs Kollo, Jaouen et Rohou : radiologie interventionnelle. Dr Rohou : imagerie abdominale. Drs Kervennic et Texier : imagerie ORL.', NULL, true, 37, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('le-centre-dispose-t-il-d-un-service-d-imagerie-de-garde-4', 18, 'Le centre dispose-t-il d''un service d''imagerie de garde ?', 'Oui, uniquement pour les patients hospitalisés à la CMBO.', NULL, true, 38, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-documents-doit-on-apporter-pour-un-examen-4', 18, 'Quels documents doit-on apporter pour un examen ?', 'Carte Vitale ou attestation avec droits à jour, le cas échéant attestation CMU/ACS ou document accident du travail/maladie professionnelle, ordonnance obligatoire (l''examen ne sera pas réalisé sans prescription médicale), examens antérieurs réalisés dans un autre centre d''imagerie (radiographies, échographies ou autres documents récents en lien avec l''examen), ainsi que les produits prescrits le cas échéant.', NULL, true, 39, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('combien-de-temps-faut-il-attendre-pour-recevoir-les-result-3', 18, 'Combien de temps faut-il attendre pour recevoir les résultats ?', 'Les résultats sont généralement disponibles sous 72 heures.', NULL, true, 40, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-la-gravure-de-cd-3', 18, 'Proposez-vous la gravure de CD ?', 'Oui, pour les scanners et les IRM.', NULL, true, 41, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-l-impression-des-cliches-sur-film-3', 18, 'Proposez-vous l''impression des clichés sur film ?', 'Non renseigné.', NULL, true, 42, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('comment-acceder-aux-resultats-d-imagerie-sur-internet-4', 18, 'Comment accéder aux résultats d''imagerie sur internet ?', 'Se connecter sur www.rim29sud.fr, onglet « VOS RÉSULTATS » puis « ACCÉDEZ À VOS RÉSULTATS », cliquer sur « Accès examen », renseigner le numéro d''examen et la date de naissance au format JJ-MM-AAAA (utiliser les tirets comme séparateur, ne pas mettre d''espace).', NULL, true, 43, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('le-compte-rendu-de-l-examen-est-il-automatiquement-envoye-4', 18, 'Le compte-rendu de l''examen est-il automatiquement envoyé à mon médecin traitant ?', 'Oui, si le médecin dispose d''une adresse sécurisée.', NULL, true, 44, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('comment-puis-je-recuperer-une-copie-de-mes-anciens-examens-4', 18, 'Comment puis-je récupérer une copie de mes anciens examens ?', 'Sur demande au centre. La réédition est facturée : 5 € pour les radiographies sur livret papier, 25 € pour les CD scanner/IRM.', NULL, true, 45, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('est-il-possible-que-les-images-soient-envoyees-directement-3', 18, 'Est-il possible que les images soient envoyées directement à un autre spécialiste si besoin ?', 'Oui, si le médecin dispose d''une adresse sécurisée.', NULL, true, 46, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('votre-centre-propose-t-il-du-wi-fi-pour-les-patients-4', 18, 'Votre centre propose-t-il du Wi-Fi pour les patients ?', 'Non.', NULL, true, 47, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('disposez-vous-d-une-salle-d-attente-adaptee-aux-enfants-4', 18, 'Disposez-vous d''une salle d''attente adaptée aux enfants ?', 'Non.', NULL, true, 48, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-vos-modes-de-paiement-acceptes-4', 18, 'Quels sont vos modes de paiement acceptés ?', 'Espèces, carte bancaire et chèque.', NULL, true, 49, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('pratiquez-vous-le-tiers-payant-4', 18, 'Pratiquez-vous le tiers payant ?', 'Le tiers payant Sécurité sociale est pratiqué. La part mutuelle ainsi que les actes HN/DH restent à la charge du patient en attente de prise en charge mutuelle éventuelle.', NULL, true, 50, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('existe-t-il-des-depassements-d-honoraires-dans-votre-centr-4', 18, 'Existe-t-il des dépassements d''honoraires dans votre centre ?', 'Oui.', NULL, true, 51, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('les-montants-des-depassements-d-honoraires-applicables', 18, 'Les montants des dépassements d''honoraires applicables ?', 'Scanner : 30 €, IRM : 35 €, Échographie : 30 €, Infiltration sous échographie : 60 €, Radiographie : 10 €, Infiltration sous radio : 60 €, Coloscopie virtuelle : 69 €.', NULL, true, 52, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-moyens-pour-deposer-une-reclamation-4', 18, 'Quels sont les moyens pour déposer une réclamation ?', 'Via les fiches de réclamation disponibles au service facturation, ou par email à : contact@29sud.fr', NULL, true, 53, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
-- 54 items generes pour userProductId=18

-- ---------------------------------------------------------------------------
-- Centre userProductId=20 (FOUESNANT.json)
-- ---------------------------------------------------------------------------
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quel-est-le-nom-complet-de-votre-centre-5', 20, 'Quel est le nom complet de votre centre ?', 'RIM29 SUD – Réseau d''Imagerie Médicale 29 Sud – site de Fouesnant', NULL, true, 0, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-complete-de-votre-centre-5', 20, 'Quelle est l''adresse complète de votre centre ?', '27 Hent Kergador – 29170 Fouesnant', NULL, true, 1, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('votre-centre-possede-t-il-un-site-web-et-si-oui-quel-est-s-5', 20, 'Votre centre possède-t-il un site web et, si oui, quel est son lien ?', 'Oui, https://www.rim29sud.fr/', NULL, true, 2, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelles-sont-les-modalites-d-acces-a-votre-centre-entree-p-5', 20, 'Quelles sont les modalités d''accès à votre centre (entrée principale, étage, interphone…) ?', 'Non renseigné.', NULL, true, 3, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-entree-recommandez-vous-aux-personnes-a-mobilite-re-4', 20, 'Quelle entrée recommandez-vous aux personnes à mobilité réduite ?', 'Accès PMR avec parking réservé. Pour les patients en brancard, il est préférable de privilégier le site de Quimper, où l''accès s''effectue avec les ambulanciers par l''arrière du bâtiment, via l''entrée des soins non programmés.', NULL, true, 4, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-phrase-dites-vous-au-telephone-au-patient-pour-lui-8', 20, 'Quelle phrase dites-vous au téléphone au patient pour lui expliquer comment se rendre à votre centre ?', 'Le centre se situe au 27 Hent Kergador, 29170 Fouesnant. Depuis Quimper, prenez la D34 en direction de Fouesnant, puis tournez à droite sur Hent Kergador.', NULL, true, 5, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-phrase-dites-vous-au-telephone-au-patient-pour-lui-9', 20, 'Quelle phrase dites-vous au téléphone au patient pour lui expliquer comment trouver l''entrée de votre centre ?', 'Le cabinet est facilement identifiable : il possède des huisseries jaunes.', NULL, true, 6, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('existe-t-il-des-difficultes-particulieres-pour-acceder-a-v-5', 20, 'Existe-t-il des difficultés particulières pour accéder à votre centre ?', 'Non.', NULL, true, 7, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('y-a-t-il-des-places-de-parking-reservees-aux-personnes-han-5', 20, 'Y a-t-il des places de parking réservées aux personnes handicapées (PMR) ?', 'Oui, sur les 3 sites.', NULL, true, 8, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('disposez-vous-d-un-parking-pour-les-patients-5', 20, 'Disposez-vous d''un parking pour les patients ?', 'Oui, sur les 3 sites.', NULL, true, 9, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-transports-en-commun-desservent-votre-centre-5', 20, 'Quels transports en commun desservent votre centre ?', 'Aucun transport en commun ne dessert le site (seul le site de Quimper est desservi, via la ligne de bus n°9).', NULL, true, 10, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelles-sont-les-heures-d-ouverture-de-votre-centre-5', 20, 'Quelles sont les heures d''ouverture de votre centre ?', 'Du lundi au vendredi de 8h30 à 12h00 et de 13h15 à 18h00.', NULL, true, 11, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelles-sont-les-heures-de-pause-ou-de-fermeture-pendant-l-5', 20, 'Quelles sont les heures de pause ou de fermeture pendant la journée ?', 'Fermeture de 12h00 à 13h15.', NULL, true, 12, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-horaires-de-disponibilite-telephonique-de-v-5', 20, 'Quels sont les horaires de disponibilité téléphonique de vos secrétaires ?', 'Du lundi au vendredi de 8h00 à 18h30, le samedi de 8h00 à 12h30.', NULL, true, 13, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-jours-ou-periodes-de-fermeture-reguliere-5', 20, 'Quels sont les jours ou périodes de fermeture régulière ?', 'Fermeture le samedi et le dimanche, ainsi que les jours fériés.', NULL, true, 14, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quel-est-le-numero-de-telephone-de-votre-secretariat-de-ra-5', 20, 'Quel est le numéro de téléphone de votre secrétariat de radiologie ?', '02 98 95 21 21', NULL, true, 15, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quel-est-le-numero-de-telephone-et-l-adresse-email-pour-co-5', 20, 'Quel est le numéro de téléphone et l''adresse email pour contacter un(e) responsable du service ?', 'Isabelle Quentel-Gourves (Responsable centre d''appels) : 02 72 88 28 42 – iquentelgourves@29sud.fr
Coat Christelle (Directrice) : 02 72 88 28 41 – ccoat@29sud.fr', NULL, true, 16, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-email-du-centre-pour-les-demandes-d-i-5', 20, 'Quelle est l''adresse email du centre pour les demandes d''information générale ?', 'contact@29sud.fr', NULL, true, 17, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-email-du-centre-pour-les-demandes-de-5', 20, 'Quelle est l''adresse email du centre pour les demandes de RDV d''examen ?', 'contact@29sud.fr', NULL, true, 18, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-email-du-centre-pour-l-envoi-par-le-p-5', 20, 'Quelle est l''adresse email du centre pour l''envoi par le patient d''ordonnances d''examen ?', 'ordo@29sud.fr (uniquement lorsqu''un rendez-vous a déjà été posé ; une réponse automatique confirme la bonne réception des documents).', NULL, true, 19, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-la-prise-de-rendez-vous-en-ligne-5', 20, 'Proposez-vous la prise de rendez-vous en ligne ?', 'Oui, via Radiobooking : https://www.rim29sud.fr/infos-rdv.html', NULL, true, 20, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-un-rappel-ou-une-confirmation-de-rendez-vous-5', 20, 'Proposez-vous un rappel ou une confirmation de rendez-vous par SMS ou email ?', 'Oui. Via Radiobooking : rappel par SMS et email. Le centre d''appels envoie également des SMS de confirmation pour tous les examens, sauf les radiographies standards où seul un rappel est transmis 24h avant le rendez-vous. Les infiltrations sous échographie ne donnent pas lieu à l''envoi de SMS.', NULL, true, 21, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('souhaitez-vous-accepter-les-nouveaux-patients-dans-lyraeta-5', 20, 'Souhaitez-vous accepter les nouveaux patients dans LyraeTalk ?', 'Non renseigné.', NULL, true, 22, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-une-liste-d-attente-ou-un-systeme-de-rappel-5', 20, 'Proposez-vous une liste d''attente ou un système de rappel pour remplacer les rendez-vous annulés ?', 'Oui. En cas d''annulation, les patients souhaitant être rappelés sont contactés par téléphone. Le rendez-vous est attribué au premier patient joignable et disponible. Aucun message vocal n''est laissé.', NULL, true, 23, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('existe-t-il-des-frais-en-cas-d-annulation-tardive-ou-d-abs-5', 20, 'Existe-t-il des frais en cas d''annulation tardive ou d''absence au rendez-vous ?', 'Non.', NULL, true, 24, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('en-cas-d-indisponibilite-de-creneau-dans-votre-centre-vers-4', 20, 'En cas d''indisponibilité de créneau dans votre centre, vers quels autres centres proposez-vous d''orienter le patient ?', 'Le réseau dispose de 3 sites (Quimper, Fouesnant, Pont-l''Abbé) et a généralement des disponibilités pour les examens courants (radiographie, échographie, mammographie). Les patients ne sont pas orientés vers d''autres structures.', NULL, true, 25, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('est-il-possible-de-choisir-son-radiologue-pour-un-examen-4', 20, 'Est-il possible de choisir son radiologue pour un examen ?', 'Oui, pour les échographies, mammographies, radiographies et ostéodensitométries.', NULL, true, 26, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-examens-que-vous-pratiquez-dans-votre-centr-5', 20, 'Quels sont les examens que vous pratiquez dans votre centre ?', 'Radiographie, mammographie, ostéodensitométrie, échographie, échodoppler.', NULL, true, 27, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('combien-de-temps-en-moyenne-le-patient-va-t-il-passer-sur-4', 20, 'Combien de temps en moyenne le patient va-t-il passer sur place pour chaque examen ?', 'Radiographie : environ 1h ; ostéodensitométrie : environ 1h ; échographie : environ 1h ; mammographie : environ 1h.', NULL, true, 28, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('votre-centre-assure-t-il-la-realisation-d-examens-en-urgen-5', 20, 'Votre centre assure-t-il la réalisation d''examens en urgence ?', 'Oui, uniquement sur rendez-vous. 2 créneaux par jour sont disponibles pour les urgences radiographiques et des créneaux sont également réservés en échographie et mammographie. Aucune urgence n''est réalisée en ostéodensitométrie.', NULL, true, 29, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('en-cas-d-examen-demande-en-urgence-est-il-possible-de-se-p-5', 20, 'En cas d''examen demandé en urgence, est-il possible de se présenter sans rendez-vous ?', 'Non, tous les examens sont réalisés uniquement sur rendez-vous.', NULL, true, 30, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('en-cas-d-urgence-medicale-quelle-consigne-donnez-vous-lors-3', 20, 'En cas d''urgence médicale, quelle consigne donnez-vous lors de la fermeture du secrétariat ?', 'En cas d''urgence vitale, appeler le 15. Sinon, se rapprocher de son médecin traitant.', NULL, true, 31, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-des-examens-interventionnels-4', 20, 'Proposez-vous des examens interventionnels ?', 'Oui, mais ces rendez-vous ne sont pas pris en charge par LyraeTalk. Un circuit dédié existe via la file d''attente n°3 du SVI.', NULL, true, 32, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('disposez-vous-d-un-irm-ouvert-ou-semi-ouvert-pour-les-pati-4', 20, 'Disposez-vous d''un IRM ouvert ou semi-ouvert pour les patients claustrophobes ?', 'Non, le site ne dispose pas d''IRM. Le site de Quimper dispose d''un IRM adapté et une prémédication peut être prescrite en cas de claustrophobie.', NULL, true, 33, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('avez-vous-des-fiches-de-consignes-pratiques-pour-la-prepar-4', 20, 'Avez-vous des fiches de consignes pratiques pour la préparation aux examens ?', 'Oui. Toutes les consignes sont données lors de la prise de rendez-vous et une fiche de consignes est expédiée au patient en fonction de l''examen.', NULL, true, 34, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('combien-de-radiologues-exercent-dans-ce-centre-4', 20, 'Combien de radiologues exercent dans ce centre ?', '14 radiologues et 3 manipulateurs échographes pour l''ensemble du réseau (3 sites).', NULL, true, 35, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-radiologues-qui-exercent-dans-votre-centre-3', 20, 'Quels sont les radiologues qui exercent dans votre centre ?', 'Radiologues résidents : Dr Bertevas-Galliou Geneviève, Dr Auter-Gestin Hervé, Dr Jaouen Alexandre, Dr Kervennic Pascal, Dr Kollo Ali, Dr Perdriel Benoit, Dr Prigent Luc, Dr Rohou Tanguy (secteur 2), Dr Texier Franck.
Radiologues vacataires : Dr Le Bihan Eric, Dr Meneux Baptiste, Dr Helias Laurent, Dr De Kermerchou, Dr Ogoundele Modeste.
Manipulateurs échographes : Albrecht Isabelle, Marchal François, Olivry Christelle.', NULL, true, 36, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('les-radiologues-sont-ils-surspecialises-par-domaine-d-imag-5', 20, 'Les radiologues sont-ils surspécialisés par domaine d''imagerie ?', 'Oui. Drs Kollo, Jaouen et Rohou : radiologie interventionnelle. Dr Rohou : imagerie abdominale. Drs Kervennic et Texier : imagerie ORL.', NULL, true, 37, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('le-centre-dispose-t-il-d-un-service-d-imagerie-de-garde-5', 20, 'Le centre dispose-t-il d''un service d''imagerie de garde ?', 'Non. La garde d''imagerie du réseau concerne uniquement les patients hospitalisés à la CMBO (site de Quimper).', NULL, true, 38, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-documents-doit-on-apporter-pour-un-examen-5', 20, 'Quels documents doit-on apporter pour un examen ?', 'Carte Vitale ou attestation avec droits à jour, le cas échéant attestation CMU/ACS ou document accident du travail/maladie professionnelle, ordonnance obligatoire (l''examen ne sera pas réalisé sans prescription médicale), examens antérieurs réalisés dans un autre centre d''imagerie (radiographies, échographies ou autres documents récents en lien avec l''examen), ainsi que les produits prescrits le cas échéant.', NULL, true, 39, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('combien-de-temps-faut-il-attendre-pour-recevoir-les-result-4', 20, 'Combien de temps faut-il attendre pour recevoir les résultats ?', 'Les résultats sont généralement disponibles sous 72 heures.', NULL, true, 40, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-la-gravure-de-cd-4', 20, 'Proposez-vous la gravure de CD ?', 'Non sur ce site : la gravure de CD concerne uniquement les scanners et les IRM, réalisés à Quimper.', NULL, true, 41, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-l-impression-des-cliches-sur-film-4', 20, 'Proposez-vous l''impression des clichés sur film ?', 'Non renseigné.', NULL, true, 42, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('comment-acceder-aux-resultats-d-imagerie-sur-internet-5', 20, 'Comment accéder aux résultats d''imagerie sur internet ?', 'Se connecter sur www.rim29sud.fr, onglet « VOS RÉSULTATS » puis « ACCÉDEZ À VOS RÉSULTATS », cliquer sur « Accès examen », renseigner le numéro d''examen et la date de naissance au format JJ-MM-AAAA (utiliser les tirets comme séparateur, ne pas mettre d''espace).', NULL, true, 43, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('le-compte-rendu-de-l-examen-est-il-automatiquement-envoye-5', 20, 'Le compte-rendu de l''examen est-il automatiquement envoyé à mon médecin traitant ?', 'Oui, si le médecin dispose d''une adresse sécurisée.', NULL, true, 44, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('comment-puis-je-recuperer-une-copie-de-mes-anciens-examens-5', 20, 'Comment puis-je récupérer une copie de mes anciens examens ?', 'Sur demande au centre. La réédition est facturée : 5 € pour les radiographies sur livret papier, 25 € pour les CD scanner/IRM.', NULL, true, 45, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('est-il-possible-que-les-images-soient-envoyees-directement-4', 20, 'Est-il possible que les images soient envoyées directement à un autre spécialiste si besoin ?', 'Oui, si le médecin dispose d''une adresse sécurisée.', NULL, true, 46, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('votre-centre-propose-t-il-du-wi-fi-pour-les-patients-5', 20, 'Votre centre propose-t-il du Wi-Fi pour les patients ?', 'Non.', NULL, true, 47, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('disposez-vous-d-une-salle-d-attente-adaptee-aux-enfants-5', 20, 'Disposez-vous d''une salle d''attente adaptée aux enfants ?', 'Non.', NULL, true, 48, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-vos-modes-de-paiement-acceptes-5', 20, 'Quels sont vos modes de paiement acceptés ?', 'Espèces, carte bancaire et chèque.', NULL, true, 49, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('pratiquez-vous-le-tiers-payant-5', 20, 'Pratiquez-vous le tiers payant ?', 'Le tiers payant Sécurité sociale est pratiqué. La part mutuelle ainsi que les actes HN/DH restent à la charge du patient en attente de prise en charge mutuelle éventuelle.', NULL, true, 50, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('existe-t-il-des-depassements-d-honoraires-dans-votre-centr-5', 20, 'Existe-t-il des dépassements d''honoraires dans votre centre ?', 'Oui.', NULL, true, 51, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('les-montants-des-depassements-d-honoraires-applicables-2', 20, 'Les montants des dépassements d''honoraires applicables ?', 'Échographie : 30 €, Infiltration sous échographie : 60 €, Radiographie : 10 €, Infiltration sous radio : 60 €.', NULL, true, 52, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-moyens-pour-deposer-une-reclamation-5', 20, 'Quels sont les moyens pour déposer une réclamation ?', 'Via les fiches de réclamation disponibles au service facturation, ou par email à : contact@29sud.fr', NULL, true, 53, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
-- 54 items generes pour userProductId=20

-- ---------------------------------------------------------------------------
-- Centre userProductId=21 (PONT-L-ABBE.json)
-- ---------------------------------------------------------------------------
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quel-est-le-nom-complet-de-votre-centre-6', 21, 'Quel est le nom complet de votre centre ?', 'RIM29 SUD – Réseau d''Imagerie Médicale 29 Sud – site de Pont-l''Abbé', NULL, true, 0, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-complete-de-votre-centre-6', 21, 'Quelle est l''adresse complète de votre centre ?', '11 Park ar Stankou – 29120 Pont-l''Abbé', NULL, true, 1, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('votre-centre-possede-t-il-un-site-web-et-si-oui-quel-est-s-6', 21, 'Votre centre possède-t-il un site web et, si oui, quel est son lien ?', 'Oui, https://www.rim29sud.fr/', NULL, true, 2, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelles-sont-les-modalites-d-acces-a-votre-centre-entree-p-6', 21, 'Quelles sont les modalités d''accès à votre centre (entrée principale, étage, interphone…) ?', 'Non renseigné.', NULL, true, 3, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-entree-recommandez-vous-aux-personnes-a-mobilite-re-5', 21, 'Quelle entrée recommandez-vous aux personnes à mobilité réduite ?', 'Accès PMR avec parking réservé. Pour les patients en brancard, il est préférable de privilégier le site de Quimper, où l''accès s''effectue avec les ambulanciers par l''arrière du bâtiment, via l''entrée des soins non programmés.', NULL, true, 4, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-phrase-dites-vous-au-telephone-au-patient-pour-lui-10', 21, 'Quelle phrase dites-vous au téléphone au patient pour lui expliquer comment se rendre à votre centre ?', 'Le centre se situe au 11 Park ar Stankou, 29120 Pont-l''Abbé. Depuis Quimper, prenez la D785 en direction de Pont-l''Abbé, puis tournez à droite sur la rue Park ar Stankou.', NULL, true, 5, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-phrase-dites-vous-au-telephone-au-patient-pour-lui-11', 21, 'Quelle phrase dites-vous au téléphone au patient pour lui expliquer comment trouver l''entrée de votre centre ?', 'Le cabinet est facilement identifiable.', NULL, true, 6, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('existe-t-il-des-difficultes-particulieres-pour-acceder-a-v-6', 21, 'Existe-t-il des difficultés particulières pour accéder à votre centre ?', 'Non.', NULL, true, 7, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('y-a-t-il-des-places-de-parking-reservees-aux-personnes-han-6', 21, 'Y a-t-il des places de parking réservées aux personnes handicapées (PMR) ?', 'Oui, sur les 3 sites.', NULL, true, 8, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('disposez-vous-d-un-parking-pour-les-patients-6', 21, 'Disposez-vous d''un parking pour les patients ?', 'Oui, sur les 3 sites.', NULL, true, 9, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-transports-en-commun-desservent-votre-centre-6', 21, 'Quels transports en commun desservent votre centre ?', 'Aucun transport en commun ne dessert le site (seul le site de Quimper est desservi, via la ligne de bus n°9).', NULL, true, 10, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelles-sont-les-heures-d-ouverture-de-votre-centre-6', 21, 'Quelles sont les heures d''ouverture de votre centre ?', 'Du lundi au vendredi de 8h30 à 12h00 et de 13h15 à 18h00.', NULL, true, 11, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelles-sont-les-heures-de-pause-ou-de-fermeture-pendant-l-6', 21, 'Quelles sont les heures de pause ou de fermeture pendant la journée ?', 'Fermeture de 12h00 à 13h15.', NULL, true, 12, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-horaires-de-disponibilite-telephonique-de-v-6', 21, 'Quels sont les horaires de disponibilité téléphonique de vos secrétaires ?', 'Du lundi au vendredi de 8h00 à 18h30, le samedi de 8h00 à 12h30.', NULL, true, 13, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-jours-ou-periodes-de-fermeture-reguliere-6', 21, 'Quels sont les jours ou périodes de fermeture régulière ?', 'Fermeture le samedi et le dimanche, ainsi que les jours fériés.', NULL, true, 14, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quel-est-le-numero-de-telephone-de-votre-secretariat-de-ra-6', 21, 'Quel est le numéro de téléphone de votre secrétariat de radiologie ?', '02 98 95 21 21', NULL, true, 15, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quel-est-le-numero-de-telephone-et-l-adresse-email-pour-co-6', 21, 'Quel est le numéro de téléphone et l''adresse email pour contacter un(e) responsable du service ?', 'Isabelle Quentel-Gourves (Responsable centre d''appels) : 02 72 88 28 42 – iquentelgourves@29sud.fr
Coat Christelle (Directrice) : 02 72 88 28 41 – ccoat@29sud.fr', NULL, true, 16, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-email-du-centre-pour-les-demandes-d-i-6', 21, 'Quelle est l''adresse email du centre pour les demandes d''information générale ?', 'contact@29sud.fr', NULL, true, 17, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-email-du-centre-pour-les-demandes-de-6', 21, 'Quelle est l''adresse email du centre pour les demandes de RDV d''examen ?', 'contact@29sud.fr', NULL, true, 18, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-email-du-centre-pour-l-envoi-par-le-p-6', 21, 'Quelle est l''adresse email du centre pour l''envoi par le patient d''ordonnances d''examen ?', 'ordo@29sud.fr (uniquement lorsqu''un rendez-vous a déjà été posé ; une réponse automatique confirme la bonne réception des documents).', NULL, true, 19, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-la-prise-de-rendez-vous-en-ligne-6', 21, 'Proposez-vous la prise de rendez-vous en ligne ?', 'Oui, via Radiobooking : https://www.rim29sud.fr/infos-rdv.html', NULL, true, 20, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-un-rappel-ou-une-confirmation-de-rendez-vous-6', 21, 'Proposez-vous un rappel ou une confirmation de rendez-vous par SMS ou email ?', 'Oui. Via Radiobooking : rappel par SMS et email. Le centre d''appels envoie également des SMS de confirmation pour tous les examens, sauf les radiographies standards où seul un rappel est transmis 24h avant le rendez-vous. Les infiltrations sous échographie ne donnent pas lieu à l''envoi de SMS.', NULL, true, 21, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('souhaitez-vous-accepter-les-nouveaux-patients-dans-lyraeta-6', 21, 'Souhaitez-vous accepter les nouveaux patients dans LyraeTalk ?', 'Non renseigné.', NULL, true, 22, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-une-liste-d-attente-ou-un-systeme-de-rappel-6', 21, 'Proposez-vous une liste d''attente ou un système de rappel pour remplacer les rendez-vous annulés ?', 'Oui. En cas d''annulation, les patients souhaitant être rappelés sont contactés par téléphone. Le rendez-vous est attribué au premier patient joignable et disponible. Aucun message vocal n''est laissé.', NULL, true, 23, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('existe-t-il-des-frais-en-cas-d-annulation-tardive-ou-d-abs-6', 21, 'Existe-t-il des frais en cas d''annulation tardive ou d''absence au rendez-vous ?', 'Non.', NULL, true, 24, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('en-cas-d-indisponibilite-de-creneau-dans-votre-centre-vers-5', 21, 'En cas d''indisponibilité de créneau dans votre centre, vers quels autres centres proposez-vous d''orienter le patient ?', 'Le réseau dispose de 3 sites (Quimper, Fouesnant, Pont-l''Abbé) et a généralement des disponibilités pour les examens courants (radiographie, échographie, mammographie). Les patients ne sont pas orientés vers d''autres structures.', NULL, true, 25, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('est-il-possible-de-choisir-son-radiologue-pour-un-examen-5', 21, 'Est-il possible de choisir son radiologue pour un examen ?', 'Oui, pour les échographies, mammographies, radiographies et ostéodensitométries.', NULL, true, 26, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-examens-que-vous-pratiquez-dans-votre-centr-6', 21, 'Quels sont les examens que vous pratiquez dans votre centre ?', 'Radiographie, mammographie, ostéodensitométrie, échographie, échodoppler.', NULL, true, 27, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('combien-de-temps-en-moyenne-le-patient-va-t-il-passer-sur-5', 21, 'Combien de temps en moyenne le patient va-t-il passer sur place pour chaque examen ?', 'Radiographie : environ 1h ; ostéodensitométrie : environ 1h ; échographie : environ 1h ; mammographie : environ 1h.', NULL, true, 28, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('votre-centre-assure-t-il-la-realisation-d-examens-en-urgen-6', 21, 'Votre centre assure-t-il la réalisation d''examens en urgence ?', 'Oui, uniquement sur rendez-vous. 2 créneaux par jour sont disponibles pour les urgences radiographiques et des créneaux sont également réservés en échographie et mammographie. Aucune urgence n''est réalisée en ostéodensitométrie.', NULL, true, 29, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('en-cas-d-examen-demande-en-urgence-est-il-possible-de-se-p-6', 21, 'En cas d''examen demandé en urgence, est-il possible de se présenter sans rendez-vous ?', 'Non, tous les examens sont réalisés uniquement sur rendez-vous.', NULL, true, 30, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('en-cas-d-urgence-medicale-quelle-consigne-donnez-vous-lors-4', 21, 'En cas d''urgence médicale, quelle consigne donnez-vous lors de la fermeture du secrétariat ?', 'En cas d''urgence vitale, appeler le 15. Sinon, se rapprocher de son médecin traitant.', NULL, true, 31, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-des-examens-interventionnels-5', 21, 'Proposez-vous des examens interventionnels ?', 'Oui, mais ces rendez-vous ne sont pas pris en charge par LyraeTalk. Un circuit dédié existe via la file d''attente n°3 du SVI.', NULL, true, 32, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('disposez-vous-d-un-irm-ouvert-ou-semi-ouvert-pour-les-pati-5', 21, 'Disposez-vous d''un IRM ouvert ou semi-ouvert pour les patients claustrophobes ?', 'Non, le site ne dispose pas d''IRM. Le site de Quimper dispose d''un IRM adapté et une prémédication peut être prescrite en cas de claustrophobie.', NULL, true, 33, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('avez-vous-des-fiches-de-consignes-pratiques-pour-la-prepar-5', 21, 'Avez-vous des fiches de consignes pratiques pour la préparation aux examens ?', 'Oui. Toutes les consignes sont données lors de la prise de rendez-vous et une fiche de consignes est expédiée au patient en fonction de l''examen.', NULL, true, 34, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('combien-de-radiologues-exercent-dans-ce-centre-5', 21, 'Combien de radiologues exercent dans ce centre ?', '14 radiologues et 3 manipulateurs échographes pour l''ensemble du réseau (3 sites).', NULL, true, 35, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-radiologues-qui-exercent-dans-votre-centre-4', 21, 'Quels sont les radiologues qui exercent dans votre centre ?', 'Radiologues résidents : Dr Bertevas-Galliou Geneviève, Dr Auter-Gestin Hervé, Dr Jaouen Alexandre, Dr Kervennic Pascal, Dr Kollo Ali, Dr Perdriel Benoit, Dr Prigent Luc, Dr Rohou Tanguy (secteur 2), Dr Texier Franck.
Radiologues vacataires : Dr Le Bihan Eric, Dr Meneux Baptiste, Dr Helias Laurent, Dr De Kermerchou, Dr Ogoundele Modeste.
Manipulateurs échographes : Albrecht Isabelle, Marchal François, Olivry Christelle.', NULL, true, 36, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('les-radiologues-sont-ils-surspecialises-par-domaine-d-imag-6', 21, 'Les radiologues sont-ils surspécialisés par domaine d''imagerie ?', 'Oui. Drs Kollo, Jaouen et Rohou : radiologie interventionnelle. Dr Rohou : imagerie abdominale. Drs Kervennic et Texier : imagerie ORL.', NULL, true, 37, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('le-centre-dispose-t-il-d-un-service-d-imagerie-de-garde-6', 21, 'Le centre dispose-t-il d''un service d''imagerie de garde ?', 'Non. La garde d''imagerie du réseau concerne uniquement les patients hospitalisés à la CMBO (site de Quimper).', NULL, true, 38, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-documents-doit-on-apporter-pour-un-examen-6', 21, 'Quels documents doit-on apporter pour un examen ?', 'Carte Vitale ou attestation avec droits à jour, le cas échéant attestation CMU/ACS ou document accident du travail/maladie professionnelle, ordonnance obligatoire (l''examen ne sera pas réalisé sans prescription médicale), examens antérieurs réalisés dans un autre centre d''imagerie (radiographies, échographies ou autres documents récents en lien avec l''examen), ainsi que les produits prescrits le cas échéant.', NULL, true, 39, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('combien-de-temps-faut-il-attendre-pour-recevoir-les-result-5', 21, 'Combien de temps faut-il attendre pour recevoir les résultats ?', 'Les résultats sont généralement disponibles sous 72 heures.', NULL, true, 40, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-la-gravure-de-cd-5', 21, 'Proposez-vous la gravure de CD ?', 'Non sur ce site : la gravure de CD concerne uniquement les scanners et les IRM, réalisés à Quimper.', NULL, true, 41, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-l-impression-des-cliches-sur-film-5', 21, 'Proposez-vous l''impression des clichés sur film ?', 'Non renseigné.', NULL, true, 42, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('comment-acceder-aux-resultats-d-imagerie-sur-internet-6', 21, 'Comment accéder aux résultats d''imagerie sur internet ?', 'Se connecter sur www.rim29sud.fr, onglet « VOS RÉSULTATS » puis « ACCÉDEZ À VOS RÉSULTATS », cliquer sur « Accès examen », renseigner le numéro d''examen et la date de naissance au format JJ-MM-AAAA (utiliser les tirets comme séparateur, ne pas mettre d''espace).', NULL, true, 43, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('le-compte-rendu-de-l-examen-est-il-automatiquement-envoye-6', 21, 'Le compte-rendu de l''examen est-il automatiquement envoyé à mon médecin traitant ?', 'Oui, si le médecin dispose d''une adresse sécurisée.', NULL, true, 44, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('comment-puis-je-recuperer-une-copie-de-mes-anciens-examens-6', 21, 'Comment puis-je récupérer une copie de mes anciens examens ?', 'Sur demande au centre. La réédition est facturée : 5 € pour les radiographies sur livret papier, 25 € pour les CD scanner/IRM.', NULL, true, 45, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('est-il-possible-que-les-images-soient-envoyees-directement-5', 21, 'Est-il possible que les images soient envoyées directement à un autre spécialiste si besoin ?', 'Oui, si le médecin dispose d''une adresse sécurisée.', NULL, true, 46, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('votre-centre-propose-t-il-du-wi-fi-pour-les-patients-6', 21, 'Votre centre propose-t-il du Wi-Fi pour les patients ?', 'Non.', NULL, true, 47, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('disposez-vous-d-une-salle-d-attente-adaptee-aux-enfants-6', 21, 'Disposez-vous d''une salle d''attente adaptée aux enfants ?', 'Non.', NULL, true, 48, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-vos-modes-de-paiement-acceptes-6', 21, 'Quels sont vos modes de paiement acceptés ?', 'Espèces, carte bancaire et chèque.', NULL, true, 49, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('pratiquez-vous-le-tiers-payant-6', 21, 'Pratiquez-vous le tiers payant ?', 'Le tiers payant Sécurité sociale est pratiqué. La part mutuelle ainsi que les actes HN/DH restent à la charge du patient en attente de prise en charge mutuelle éventuelle.', NULL, true, 50, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('existe-t-il-des-depassements-d-honoraires-dans-votre-centr-6', 21, 'Existe-t-il des dépassements d''honoraires dans votre centre ?', 'Oui.', NULL, true, 51, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('les-montants-des-depassements-d-honoraires-applicables-3', 21, 'Les montants des dépassements d''honoraires applicables ?', 'Échographie : 30 €, Infiltration sous échographie : 60 €, Radiographie : 10 €, Infiltration sous radio : 60 €.', NULL, true, 52, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-moyens-pour-deposer-une-reclamation-6', 21, 'Quels sont les moyens pour déposer une réclamation ?', 'Via les fiches de réclamation disponibles au service facturation, ou par email à : contact@29sud.fr', NULL, true, 53, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
-- 54 items generes pour userProductId=21

-- ---------------------------------------------------------------------------
-- Centre userProductId=22 (PONTIVY.json)
-- ---------------------------------------------------------------------------
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quel-est-le-nom-complet-de-votre-centre-7', 22, 'Quel est le nom complet de votre centre ?', 'Groupe Hospitalier Centre Bretagne (GHCB) – Service d''Imagerie Médicale', NULL, true, 0, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-complete-de-votre-centre-7', 22, 'Quelle est l''adresse complète de votre centre ?', 'Kerio – 56920 Noyal-Pontivy', NULL, true, 1, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('votre-centre-possede-t-il-un-site-web-et-si-oui-quel-est-s-7', 22, 'Votre centre possède-t-il un site web et, si oui, quel est son lien ?', 'Oui, https://www.ch-centre-bretagne.fr/', NULL, true, 2, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelles-sont-les-modalites-d-acces-a-votre-centre-entree-p-7', 22, 'Quelles sont les modalités d''accès à votre centre (entrée principale, étage, interphone…) ?', 'Le service dispose d''un accès dédié, accessible directement depuis l''extérieur. Il est situé en rez-de-chaussée.', NULL, true, 3, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-entree-recommandez-vous-aux-personnes-a-mobilite-re-6', 22, 'Quelle entrée recommandez-vous aux personnes à mobilité réduite ?', 'L''accès au service d''imagerie se fait depuis l''entrée extérieure dédiée, à droite du service des urgences.', NULL, true, 4, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-phrase-dites-vous-au-telephone-au-patient-pour-lui-12', 22, 'Quelle phrase dites-vous au téléphone au patient pour lui expliquer comment se rendre à votre centre ?', 'Aucune phrase n''est utilisée actuellement. Si besoin : « L''accès au service d''imagerie se fait depuis l''entrée extérieure dédiée, à droite du service des urgences. »', NULL, true, 5, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-phrase-dites-vous-au-telephone-au-patient-pour-lui-13', 22, 'Quelle phrase dites-vous au téléphone au patient pour lui expliquer comment trouver l''entrée de votre centre ?', 'L''entrée se situe entre l''entrée des Urgences et la Polyclinique.', NULL, true, 6, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('existe-t-il-des-difficultes-particulieres-pour-acceder-a-v-7', 22, 'Existe-t-il des difficultés particulières pour accéder à votre centre ?', 'Non.', NULL, true, 7, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('y-a-t-il-des-places-de-parking-reservees-aux-personnes-han-7', 22, 'Y a-t-il des places de parking réservées aux personnes handicapées (PMR) ?', 'Oui, juste devant l''entrée du service.', NULL, true, 8, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('disposez-vous-d-un-parking-pour-les-patients-7', 22, 'Disposez-vous d''un parking pour les patients ?', 'Oui, devant l''hôpital.', NULL, true, 9, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-transports-en-commun-desservent-votre-centre-7', 22, 'Quels transports en commun desservent votre centre ?', 'Pondibus ligne 5, arrêt Hôpital. BreizhGo, axe Saint-Brieuc / Vannes ou Lorient.', NULL, true, 10, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelles-sont-les-heures-d-ouverture-de-votre-centre-7', 22, 'Quelles sont les heures d''ouverture de votre centre ?', 'Le service d''Imagerie Médicale est ouvert de 7h45 à 19h00 sans interruption.', NULL, true, 11, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelles-sont-les-heures-de-pause-ou-de-fermeture-pendant-l-7', 22, 'Quelles sont les heures de pause ou de fermeture pendant la journée ?', 'Aucune : il n''y a pas de fermeture sur le temps du midi.', NULL, true, 12, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-horaires-de-disponibilite-telephonique-de-v-7', 22, 'Quels sont les horaires de disponibilité téléphonique de vos secrétaires ?', 'Le secrétariat téléphonique est ouvert de 8h30 à 17h30 sans interruption.', NULL, true, 13, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-jours-ou-periodes-de-fermeture-reguliere-7', 22, 'Quels sont les jours ou périodes de fermeture régulière ?', 'Le secrétariat téléphonique est ouvert du lundi au vendredi. Pas de réponse les samedis, dimanches et jours fériés.', NULL, true, 14, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quel-est-le-numero-de-telephone-de-votre-secretariat-de-ra-7', 22, 'Quel est le numéro de téléphone de votre secrétariat de radiologie ?', '02 97 79 00 10 (radiographie, scanner, IRM, échographie, échodoppler)
02 97 79 09 39 (mammographie et échographie mammaire)', NULL, true, 15, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quel-est-le-numero-de-telephone-et-l-adresse-email-pour-co-7', 22, 'Quel est le numéro de téléphone et l''adresse email pour contacter un(e) responsable du service ?', 'Laurence Viallard : 02 97 79 03 92 – Laurence.viallard@gh-centrebretagne.fr', NULL, true, 16, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-email-du-centre-pour-les-demandes-d-i-7', 22, 'Quelle est l''adresse email du centre pour les demandes d''information générale ?', 'Secretariat.imagerie@gh-centrebretagne.fr', NULL, true, 17, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-email-du-centre-pour-les-demandes-de-7', 22, 'Quelle est l''adresse email du centre pour les demandes de RDV d''examen ?', 'Radiographie, scanner, IRM, échographie, échodoppler : Secretariat.imagerie@gh-centrebretagne.fr
Mammographie et échographie mammaire : Secretariat.mammographie@gh-centrebretagne.fr', NULL, true, 18, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quelle-est-l-adresse-email-du-centre-pour-l-envoi-par-le-p-7', 22, 'Quelle est l''adresse email du centre pour l''envoi par le patient d''ordonnances d''examen ?', 'Radiographie, scanner, IRM, échographie, échodoppler : Secretariat.imagerie@gh-centrebretagne.fr
Mammographie et échographie mammaire : Secretariat.mammographie@gh-centrebretagne.fr', NULL, true, 19, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-la-prise-de-rendez-vous-en-ligne-7', 22, 'Proposez-vous la prise de rendez-vous en ligne ?', 'Non (mais cela pourrait être mis en place dans un second temps).', NULL, true, 20, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-un-rappel-ou-une-confirmation-de-rendez-vous-7', 22, 'Proposez-vous un rappel ou une confirmation de rendez-vous par SMS ou email ?', 'SMS de rappel : oui. SMS de confirmation : non. Email : non.', NULL, true, 21, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('souhaitez-vous-accepter-les-nouveaux-patients-dans-lyraeta-7', 22, 'Souhaitez-vous accepter les nouveaux patients dans LyraeTalk ?', 'Oui.', NULL, true, 22, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-une-liste-d-attente-ou-un-systeme-de-rappel-7', 22, 'Proposez-vous une liste d''attente ou un système de rappel pour remplacer les rendez-vous annulés ?', 'Oui, via le filtre « SI DÉSISTEMENT » dans Xplore.', NULL, true, 23, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('existe-t-il-des-frais-en-cas-d-annulation-tardive-ou-d-abs-7', 22, 'Existe-t-il des frais en cas d''annulation tardive ou d''absence au rendez-vous ?', 'Non.', NULL, true, 24, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('en-cas-d-indisponibilite-de-creneau-dans-votre-centre-vers-6', 22, 'En cas d''indisponibilité de créneau dans votre centre, vers quels autres centres proposez-vous d''orienter le patient ?', 'Aucun : les patients ne sont pas orientés vers d''autres centres.', NULL, true, 25, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('est-il-possible-de-choisir-son-radiologue-pour-un-examen-6', 22, 'Est-il possible de choisir son radiologue pour un examen ?', 'Non.', NULL, true, 26, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-examens-que-vous-pratiquez-dans-votre-centr-7', 22, 'Quels sont les examens que vous pratiquez dans votre centre ?', 'IRM, scanner, mammographie (50-74 ans), échographie mammaire, échographie, échodoppler, radiographie.', NULL, true, 27, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('combien-de-temps-en-moyenne-le-patient-va-t-il-passer-sur-6', 22, 'Combien de temps en moyenne le patient va-t-il passer sur place pour chaque examen ?', 'IRM : 1h30 ; scanner : 30 minutes ; mammographie : 1h ; échographie mammaire : 45 minutes ; échographie : 1h ; échodoppler : 45 minutes ; radiographie : 45 minutes.', NULL, true, 28, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('votre-centre-assure-t-il-la-realisation-d-examens-en-urgen-7', 22, 'Votre centre assure-t-il la réalisation d''examens en urgence ?', 'Oui, le caractère urgent de l''examen est déterminé par le radiologue.', NULL, true, 29, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('en-cas-d-examen-demande-en-urgence-est-il-possible-de-se-p-7', 22, 'En cas d''examen demandé en urgence, est-il possible de se présenter sans rendez-vous ?', 'Non.', NULL, true, 30, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('en-cas-d-urgence-medicale-quelle-consigne-donnez-vous-lors-5', 22, 'En cas d''urgence médicale, quelle consigne donnez-vous lors de la fermeture du secrétariat ?', 'En cas d''urgence, et en dehors des heures ouvrables de votre médecin, contactez les urgences au 02 97 79 00 35.', NULL, true, 31, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-des-examens-interventionnels-6', 22, 'Proposez-vous des examens interventionnels ?', 'Non, sauf pour les biopsies mammaires.', NULL, true, 32, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('disposez-vous-d-un-irm-ouvert-ou-semi-ouvert-pour-les-pati-6', 22, 'Disposez-vous d''un IRM ouvert ou semi-ouvert pour les patients claustrophobes ?', 'Non.', NULL, true, 33, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('avez-vous-des-fiches-de-consignes-pratiques-pour-la-prepar-6', 22, 'Avez-vous des fiches de consignes pratiques pour la préparation aux examens ?', 'Oui.', NULL, true, 34, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('combien-de-radiologues-exercent-dans-ce-centre-6', 22, 'Combien de radiologues exercent dans ce centre ?', '4 radiologues et 2 angiologues.', NULL, true, 35, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-radiologues-qui-exercent-dans-votre-centre-5', 22, 'Quels sont les radiologues qui exercent dans votre centre ?', 'Radiologues : Dr Ghannam, Dr Estable, Dr Habert, Dr Foudi.
Angiologues : Dr Nouni, Dr Faugaret.', NULL, true, 36, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('les-radiologues-sont-ils-surspecialises-par-domaine-d-imag-7', 22, 'Les radiologues sont-ils surspécialisés par domaine d''imagerie ?', 'Oui. Dr Ghannam : imagerie abdomino-pelvienne. Dr Estable : neuroradiologie. Dr Habert : mammographie et échographie mammaire. Dr Foudi : imagerie ostéo-articulaire. Dr Nouni et Dr Faugaret : pas de surspécialité renseignée.', NULL, true, 37, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('le-centre-dispose-t-il-d-un-service-d-imagerie-de-garde-7', 22, 'Le centre dispose-t-il d''un service d''imagerie de garde ?', 'Non.', NULL, true, 38, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-documents-doit-on-apporter-pour-un-examen-7', 22, 'Quels documents doit-on apporter pour un examen ?', 'Pièce d''identité, carte Vitale, mutuelle en cours de validité, ordonnance, document lié à un accident du travail le cas échéant, et pour les mineurs le livret de famille.', NULL, true, 39, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('combien-de-temps-faut-il-attendre-pour-recevoir-les-result-6', 22, 'Combien de temps faut-il attendre pour recevoir les résultats ?', 'Entre 24 et 72 heures ouvrées.', NULL, true, 40, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-la-gravure-de-cd-6', 22, 'Proposez-vous la gravure de CD ?', 'Non.', NULL, true, 41, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('proposez-vous-l-impression-des-cliches-sur-film-6', 22, 'Proposez-vous l''impression des clichés sur film ?', 'Oui, uniquement pour la mammographie.', NULL, true, 42, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('comment-acceder-aux-resultats-d-imagerie-sur-internet-7', 22, 'Comment accéder aux résultats d''imagerie sur internet ?', 'Les images sont accessibles avec les codes remis aux patients lors de leur examen.', NULL, true, 43, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('le-compte-rendu-de-l-examen-est-il-automatiquement-envoye-7', 22, 'Le compte-rendu de l''examen est-il automatiquement envoyé à mon médecin traitant ?', 'Oui.', NULL, true, 44, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('comment-puis-je-recuperer-une-copie-de-mes-anciens-examens-7', 22, 'Comment puis-je récupérer une copie de mes anciens examens ?', 'Sur demande par email à : Secretariat.imagerie@gh-centrebretagne.fr', NULL, true, 45, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('est-il-possible-que-les-images-soient-envoyees-directement-6', 22, 'Est-il possible que les images soient envoyées directement à un autre spécialiste si besoin ?', 'Oui, sur demande du médecin en ayant besoin, à l''adresse : Referentspacs@gh-centrebretagne.fr', NULL, true, 46, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('votre-centre-propose-t-il-du-wi-fi-pour-les-patients-7', 22, 'Votre centre propose-t-il du Wi-Fi pour les patients ?', 'Oui.', NULL, true, 47, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('disposez-vous-d-une-salle-d-attente-adaptee-aux-enfants-7', 22, 'Disposez-vous d''une salle d''attente adaptée aux enfants ?', 'Non.', NULL, true, 48, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-vos-modes-de-paiement-acceptes-7', 22, 'Quels sont vos modes de paiement acceptés ?', 'Chèque et carte bancaire.', NULL, true, 49, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('pratiquez-vous-le-tiers-payant-7', 22, 'Pratiquez-vous le tiers payant ?', 'Oui, tiers payant sécurité sociale et mutuelle.', NULL, true, 50, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('existe-t-il-des-depassements-d-honoraires-dans-votre-centr-7', 22, 'Existe-t-il des dépassements d''honoraires dans votre centre ?', 'Non.', NULL, true, 51, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('les-montants-des-depassements-d-honoraires-applicables-4', 22, 'Les montants des dépassements d''honoraires applicables ?', 'Sans objet (aucun dépassement d''honoraires).', NULL, true, 52, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "ModuleInfoItem" ("id", "userProductId", "question", "reponse", "categorie", "enabled", "order", "createdAt", "updatedAt") VALUES ('quels-sont-les-moyens-pour-deposer-une-reclamation-7', 22, 'Quels sont les moyens pour déposer une réclamation ?', 'Par courrier adressé à la Direction des Relations avec les Usagers – GHCB – 56920 Noyal-Pontivy, ou par email à : relations.usagers@gh-centrebretagne.fr', NULL, true, 53, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
-- 54 items generes pour userProductId=22

-- Bump moduleInfoVersion pour les 4 centres
UPDATE "UserProduct" SET "moduleInfoVersion" = NOW() WHERE "id" = 18;
UPDATE "UserProduct" SET "moduleInfoVersion" = NOW() WHERE "id" = 20;
UPDATE "UserProduct" SET "moduleInfoVersion" = NOW() WHERE "id" = 21;
UPDATE "UserProduct" SET "moduleInfoVersion" = NOW() WHERE "id" = 22;

COMMIT;

-- TOTAL : 216 items inseres
